<?php

define('ID', 0);
define('CHAPTER', 4);
define('QUESTION', 5);
define('CHOICES', 6);
define('NUM_URBAN', 1);
define('NUM_RURAL', 2);
define('NUM_TOTAL', 3);
define('TXT_URBAN', 7);
define('TXT_RURAL', 8);
define('TXT_TOTAL', 9);

$workbook = new \PHPExcel();

// headers
$row = 1;



$workbook->getActiveSheet()->mergeCells('E'.$row.':G'.$row);
$workbook->getActiveSheet()->mergeCells('H'.$row.':J'.$row);
$workbook->getActiveSheet()->setCellValueByColumnAndRow(NUM_URBAN, $row, 'Numerical');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(TXT_URBAN, $row, 'Text');

$row++;
$workbook->getActiveSheet()->setCellValueByColumnAndRow(ID, $row, 'ID');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(CHAPTER, $row, 'Chapter');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(QUESTION, $row, 'Question');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(CHOICES, $row, 'Choices');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(NUM_URBAN, $row, 'Urban');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(NUM_RURAL, $row, 'Rural');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(NUM_TOTAL, $row, 'Total');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(TXT_URBAN, $row, 'Urban');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(TXT_RURAL, $row, 'Rural');
$workbook->getActiveSheet()->setCellValueByColumnAndRow(TXT_TOTAL, $row, 'Total');


foreach ($questions as $question) {
    $row++;

    switch ($question['type']) {
        case 'Chapter':
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(ID, $row, $question['id']);
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(CHAPTER, $row, $question['name']);
            break;

        case 'Numeric':
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(ID, $row,  $question['id']);
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(QUESTION, $row, $question['name']);
            //insertParts('num', $question, $row, $workbook);
            break;

        case 'Text':
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(ID, $row,  $question['id']);
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(QUESTION, $row, $question['name']);
            insertParts('txt', $question, $row, $workbook);
            break;

        case 'User':
        case 'Choice':
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(ID, $row,  $question['id']);
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(QUESTION, $row, $question['name']);
            insertChoices($question, $row, $workbook);
            break;
    }
}

$this->excelSend($workbook);







function insertParts($type, $question, $row, $workbook, $choice=null)
{
    foreach ($question['parts'] as $part) {

        switch ($part['name']) {
            case 'Urban' :
                switch ($type) {
                    case 'num' : $col = NUM_URBAN; break;
                    case 'txt' : $col = TXT_URBAN; break;
                }
                break;
            case 'Rural' :
                switch ($type) {
                    case 'num' : $col = NUM_RURAL; break;
                    case 'txt' : $col = TXT_RURAL; break;
                }
                break;
            case 'Total' :
                switch ($type) {
                    case 'num' : $col = NUM_TOTAL; break;
                    case 'txt' : $col = TXT_TOTAL; break;
                }
                break;
        }
        //echo '('.$col.'-'.$row.")\n";
        $workbook->getActiveSheet()->setCellValueByColumnAndRow($col, $row, getAnswer($question, $part, $choice));
    }
}



function insertChoices ($question, &$row, $workbook)
{
    if ($question['isMultiple']){
        foreach ($question['choices'] as $choice) {
            $row++;
            $workbook->getActiveSheet()->setCellValueByColumnAndRow(CHOICES, $row, $choice['label']);
            insertParts('num', $question, $row, $workbook, $choice);
        }
    } else {
        insertParts('num', $question, $row, $workbook);
    }
}



function getAnswer ($question, $part, $choice) {

    foreach ($question['answers'] as $answer) {
        if ((isset($question['isMultiple']) && $question['isMultiple'] && $answer['valueChoice']==$choice['id'] && $answer['part']['id']==$part['id']) ||
            ((!isset($question['isMultiple']) || !$question['isMultiple']) && $answer['part']['id']==$part['id'])
        ) {
            return $answer['valuePercent'].$answer['valueAbsolute'].$answer['valueText'];
        }
    }
    return '';
}





