<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-user"></i></span>
            <li><a href="/admin/user">Users</a></li>
            <li class="active">{{user.name}}</li>
        </ul>
    </h2>

    <?php echo $this->helpBox('Edit the user\'s account and his access rights. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/user.html">detailed documentation</a>.'); ?>

    <form name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('user'); ?>

        <tabset style="margin-top: 20px">
            <tab heading="General">

                <div class="form-group" ng-class="{'has-error': myForm.name.$invalid}">
                    <label class="control-label col-sm-1" for="user.name"><?php echo $this->translate("Name"); ?></label>
                    <div class="col-sm-6">
                        <input id="user.name" type="text" name="name" ng-model="user.name" required ng-minlength="3"/>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.name.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                        <span ng-show="myForm.name.$error.minlength" class="help-block"><?php echo sprintf($this->translate("It must be at least %u characters long"), 3); ?></span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.email.$invalid}">
                    <label class="control-label col-sm-1" for="user.email"><?php echo $this->translate("Email"); ?></label>
                    <div class="col-sm-6">
                        <input id="user.email" type="email" name="email" ng-model="user.email" required />
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.email.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                        <span ng-show="myForm.email.$error.email" class="help-block"><?php echo $this->translate('Enter a valid email address'); ?></span>
                    </div>
                </div>

                <div class="form-group" ng-if="!user.id" ng-class="{'has-error': myForm.password.$invalid || myForm.passwordVerify.$invalid}">
                    <label class="control-label col-sm-1" for="user.password"><?php echo $this->translate("Password"); ?></label>

                    <div class="col-sm-11">

                        <div class="row">
                            <div class="col-sm-5">
                                <input id="user.password" name="password" type="password" autocomplete="off" ng-model="user.password" placeholder="password" ng-minlength="6">
                            </div>
                            <div class="col-sm-3">
                                <span ng-show="myForm.password.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                                <span ng-show="myForm.password.$error.minlength" class="help-block"><?php echo sprintf($this->translate("It must be at least %u characters long"), 6); ?></span>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-sm-5">
                                <input name="passwordVerify" type="password" ng-model="user.passwordVerify" ui-validate=" '$value==user.password' " ui-validate-watch=" 'user.password' " placeholder="confirm password" >
                            </div>
                            <div class="col-sm-3">
                                <span ng-show="myForm.passwordVerify.$error.validator" class="help-block"><?php echo $this->translate("Passwords do not match!"); ?></span>
                            </div>
                        </div>

                    </div>
                </div>


                <div class="form-group" ng-class="{'has-error': myForm.phone.$invalid}">
                    <label class="control-label col-sm-1" for="user.phone">Phone</label>
                    <div class="col-sm-6">
                        <input id="user.phone" type="text" name="phone" ng-model="user.phone"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.skype.$invalid}">
                    <label class="control-label col-sm-1" for="user.skype">Skype</label>
                    <div class="col-sm-6">
                        <input id="user.skype" type="text" name="skype" ng-model="user.skype"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.job.$invalid}">
                    <label class="control-label col-sm-1" for="user.job">Job title</label>
                    <div class="col-sm-6">
                        <input id="user.job" type="text" name="job" ng-model="user.job"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.ministry.$invalid}">
                    <label class="control-label col-sm-1" for="user.ministry">Ministry / Departement</label>
                    <div class="col-sm-6">
                        <input id="user.ministry" type="text" name="ministry" ng-model="user.ministry"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.address.$invalid}">
                    <label class="control-label col-sm-1" for="user.address">Address</label>
                    <div class="col-sm-6">
                        <textarea id="user.address" type="text" name="address" ng-model="user.address" ></textarea>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.zip.$invalid}">
                    <label class="control-label col-sm-1" for="user.zip">ZIP</label>
                    <div class="col-sm-6">
                        <input id="user.zip" type="text" name="zip" ng-model="user.zip"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.city.$invalid}">
                    <label class="control-label col-sm-1" for="user.city">City</label>
                    <div class="col-sm-6">
                        <input id="user.city" type="text" name="city" ng-model="user.city"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.country.$invalid}">
                    <label class="control-label col-sm-1" for="country">Country</label>
                    <div class="col-sm-6">
                        <gims-select id="country" api="country" name="country" model="user.country" style="width:100%"></gims-select>
                    </div>
                </div>

            </tab>

            <tab heading="Surveys" ng-if="user.id">
                <gims-relations relation="UserSurvey" properties="['user', 'survey', 'role']"></gims-relations>
            </tab>

            <tab heading="Questionnaires" ng-if="user.id">
                <gims-relations relation="UserQuestionnaire" properties="['user', 'questionnaire', 'role']"></gims-relations>
            </tab>

            <tab heading="Filter Sets" ng-if="user.id">
                <gims-relations relation="UserFilterSet" properties="['user', 'filterSet', 'role']"></gims-relations>
            </tab>
        </tabset>
    </form>
    <?php echo $this->metadata('user'); ?>
</div> <!-- /container -->
