<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-user"></i></span>
            <li><a href="/admin/user">Users</a></li>
            <li class="active">{{user.name}}</li>
        </ul>
    </h2>

    <?php echo $this->helpBox('Edit the user\'s account and his access rights. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/user.html">detailed documentation</a>.'); ?>
    <div ng-if="firstLogin" class="alert alert-warning"><i class="fa fa-warning"></i> Please take a moment to complete your profile.</div>

    <form name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('user'); ?>

        <tabset style="margin-top: 20px">
            <tab heading="General" active="tabs[0]" select="selectTab(0)">

                <div class="form-group" ng-class="{'has-error': myForm.name.$invalid}"  style="position: relative;">
                    <img ng-src="{{user.gravatar}}&s=128" style="position: absolute; right: 40px" class="hidden-xs"/>
                    <label class="control-label col-sm-2" for="user.name"><?php echo $this->translate("Name"); ?></label>
                    <div class="col-sm-5">
                        <input id="user.name" type="text" class="form-control" name="name" ng-model="user.name" required ng-minlength="3"/>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.name.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                        <span ng-show="myForm.name.$error.minlength" class="help-block"><?php echo sprintf($this->translate("It must be at least %u characters long"), 3); ?></span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.email.$invalid}">
                    <label class="control-label col-sm-2" for="user.email"><?php echo $this->translate("Email"); ?></label>
                    <div class="col-sm-5">
                        <input id="user.email" type="email" class="form-control" name="email" ng-model="user.email" required />
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.email.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                        <span ng-show="myForm.email.$error.email" class="help-block"><?php echo $this->translate('Enter a valid email address'); ?></span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2"><?php echo $this->translate("Password"); ?></label>
                    <div class="col-sm-3">
                        <a class='btn btn-link' ng-click="sendChangePassword()" ng-if="!myForm.email.$invalid">Change password</a>
                        <a class='btn text-muted' ng-if="myForm.email.$invalid">Change password</a>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="changePasswordSent" class="help-block"><?php echo $this->translate('An email has been sent to'); ?> {{user.email}}</span>
                        <span ng-show="changePasswordNotSent" class="help-block"><?php echo $this->translate('An error occured, contact and '); ?></span>
                    </div>
                </div>
                <div class="form-group" ng-if="!user.id" ng-class="{'has-error': myForm.password.$invalid || myForm.passwordVerify.$invalid}">
                    <label class="control-label col-sm-2" for="user.password"><?php echo $this->translate("Password"); ?></label>

                    <div class="col-sm-11">

                        <div class="row">
                            <div class="col-sm-5">
                                <input id="user.password" name="password" type="password" class="form-control" autocomplete="off" ng-model="user.password" placeholder="password" ng-minlength="6">
                            </div>
                            <div class="col-sm-3">
                                <span ng-show="myForm.password.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                                <span ng-show="myForm.password.$error.minlength" class="help-block"><?php echo sprintf($this->translate("It must be at least %u characters long"), 6); ?></span>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="col-sm-5">
                                <input name="passwordVerify" type="password" class="form-control" ng-model="user.passwordVerify" ui-validate=" '$value==user.password' " ui-validate-watch=" 'user.password' " placeholder="confirm password" >
                            </div>
                            <div class="col-sm-3">
                                <span ng-show="myForm.passwordVerify.$error.validator" class="help-block"><?php echo $this->translate("Passwords do not match!"); ?></span>
                            </div>
                        </div>

                    </div>
                </div>


                <div class="form-group" ng-class="{'has-error': myForm.phone.$invalid}">
                    <label class="control-label col-sm-2" for="user.phone">Phone</label>
                    <div class="col-sm-5">
                        <input id="user.phone" type="text" class="form-control" name="phone" ng-model="user.phone"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.skype.$invalid}">
                    <label class="control-label col-sm-2" for="user.skype">Skype</label>
                    <div class="col-sm-5">
                        <input id="user.skype" type="text" class="form-control" name="skype" ng-model="user.skype"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.job.$invalid}">
                    <label class="control-label col-sm-2" for="user.job">Job title</label>
                    <div class="col-sm-5">
                        <input id="user.job" type="text" class="form-control" name="job" ng-model="user.job"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.ministry.$invalid}">
                    <label class="control-label col-sm-2" for="user.ministry">Ministry / Departement</label>
                    <div class="col-sm-5">
                        <input id="user.ministry" type="text" class="form-control" name="ministry" ng-model="user.ministry"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.address.$invalid}">
                    <label class="control-label col-sm-2" for="user.address">Address</label>
                    <div class="col-sm-5">
                        <textarea id="user.address" class="form-control" name="address" ng-model="user.address" ></textarea>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.zip.$invalid}">
                    <label class="control-label col-sm-2" for="user.zip">ZIP</label>
                    <div class="col-sm-5">
                        <input id="user.zip" type="text" class="form-control" name="zip" ng-model="user.zip"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.city.$invalid}">
                    <label class="control-label col-sm-2" for="user.city">City</label>
                    <div class="col-sm-5">
                        <input id="user.city" type="text" class="form-control" name="city" ng-model="user.city"/>
                    </div>
                </div>
                <div class="form-group" ng-class="{'has-error': myForm.geoname.$invalid}">
                    <label class="control-label col-sm-2" for="geoname">Country</label>
                    <div class="col-sm-5">
                        <gims-select id="geoname" api="geoname" name="geoname" model="user.geoname" change-url="false" style="width:100%"></gims-select>
                    </div>
                </div>

            </tab>

            <tab heading="Surveys" ng-if="user.id" active="tabs[1]" select="selectTab(1)">
                <gims-relations relation="UserSurvey" properties="['user', 'survey', 'role']"></gims-relations>
            </tab>

            <tab heading="Questionnaires" ng-if="user.id" active="tabs[2]" select="selectTab(2)">
                <gims-relations relation="UserQuestionnaire" properties="['user', 'questionnaire', 'role']"></gims-relations>
            </tab>

            <tab heading="Filter Sets" ng-if="user.id" active="tabs[3]" select="selectTab(3)">
                <gims-relations relation="UserFilterSet" properties="['user', 'filterSet', 'role']"></gims-relations>
            </tab>

            <tab heading="Activity" ng-if="user.id" active="tabs[4]" select="selectTab(4)">
                <gims-activity user="user"></gims-activity>
            </tab>
        </tabset>
    </form>
    <?php echo $this->metadata('user'); ?>
</div> <!-- /container -->
