<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li><a href="/admin/user">Users</a></li>
            <li class="active">{{user.name}}</li>
        </ul>
    </h2>
    <form name="myForm">

        <?php echo $this->crudButtons('user'); ?>

        <tabs style="margin-top: 20px">
            <pane heading="General info">

                <div class="control-group" ng-class="{error: myForm.name.$invalid}">
                    <label for="user.name">Name</label>
                    <input id="user.name" type="text" name="name" ng-model="user.name" required class="span6" ng-minlength="3"/>
                    <span ng-show="myForm.name.$error.required" class="help-inline">Required</span>
                    <span ng-show="myForm.name.$error.minlength" class="help-inline">It must be at least 3 character long</span>
                </div>

                <div class="control-group" ng-class="{error: myForm.email.$invalid}">
                    <label for="user.email">Email</label>
                    <input id="user.email" type="email" name="email" ng-model="user.email" required class="span6"  />
                    <span ng-show="myForm.email.$error.required" class="help-inline">Required</span>
                </div>

                <div class="control-group" ng-class="{error: myForm.password.$invalid || myForm.passwordVerify.$invalid}">
                    <label for="user.password">Password</label>
                    <input id="user.password" name="password" type="password" ng-model="user.password" placeholder="password" class="span6" ng-minlength="6">
                    <span ng-show="myForm.password.$error.required" class="help-inline">Required</span>
                    <span ng-show="myForm.password.$error.minlength" class="help-inline">It must be at least 6 character long</span>
                    <br>
                    <input name="passwordVerify" type="password" ng-model="user.passwordVerify" ui-validate=" '$value==user.password' " ui-validate-watch=" 'user.password' " placeholder="confirm password"  class="span6">
                    <span ng-show="myForm.passwordVerify.$error.validator" class="help-inline">Passwords do not match!</span>
                </div>

                <!--
                <div class="control-group" ng-class="{error: myForm.state.$invalid}">
                    <label for="user.state">State</label>
                    <select id="user.state" name="state" ng-model="user.state" ng-options="c.value as c.text for c in states"
                            required></select>
                    <span ng-show="myForm.state.$error.required" class="help-inline">Required</span>
                </div> -->
            </pane>

            <pane heading="Surveys">

                <div class="row-fluid">
                    <div class="span9">
                        <input type="text" ng-model="filteringText" placeholder="Search..." class="search" style="width: 400px"/>
                    </div>
                </div>

                <div ng-grid="gridSurveyOptions" class="gridStyle"></div>

                <div class="well" ng-show="user.id">
                    <span class="span4">
                        <input name="survey" ui-select2="select2.survey.list" ng-model="select2.survey.selected" data-placeholder="<?php echo $this->translate('Select a survey') ?>"  style="width:100%;"/>
                    </span>
                    <span class="span4">
                        <input name="role" ui-select2="select2.role.list" ng-model="select2.role.selected" data-placeholder="<?php echo $this->translate('Select a role') ?>"  style="width:100%;"/>
                    </span>
                    <span class="span1">
                        <button class="btn" ng-click="addUserSurvey()"><?php echo $this->translate('Add') ?></button>
                        <i class="icon-loading" ng-show="isLoading"></i>
                    </span>
                </div>

            </pane>

            <pane heading="Questionnaires">

                <div class="row-fluid">
                    <div class="span9">
                        <input type="text" ng-model="filteringText" placeholder="Search..." class="search" style="width: 400px"/>
                    </div>
                    <div class="span3" style="text-align: right">
                        <a href="/admin/user/new"><i class="icon-plus-sign"></i> new user</a>
                    </div>
                </div>

                <div ng-grid="gridQuestionnaireOptions" class="gridStyle"></div>
            </pane>
        </tabs>
    </form>
    <?php echo $this->metadata('user'); ?>
</div> <!-- /container -->
