<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li class="active"><a href="/admin/user">Users</a></li>
        </ul>
    </h2>

    <div class="row-fluid">
        <div class="span9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search" style="width: 400px"/>
        </div>
        <div class="span3" style="text-align: right">
            <a href="/admin/user/new"><i class="icon-plus-sign"></i> new user</a>
        </div>
    </div>

    <div ng-grid="gridOptions" class="gridStyle"></div>

</div> <!-- /container -->
