<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li class="active"><a href="/admin/user">Users</a></li>
        </ul>
    </h2>

    <div class="row show-grid">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search" style="width: 400px"/>
        </div>
        <div class="col-md-3" style="text-align: right">
            <gims-link-new target='user'></gims-link-new>
        </div>
    </div>

    <gims-grid api="user" options="gridOptions"></gims-grid>

</div> <!-- /container -->
