<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-user"></i></span>
            <li class="active"><a href="/admin/user">Users</a></li>
        </ul>
    </h2>

    <?php echo $this->helpBox('Create new users and edit their accounts. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/user.html">detailed documentation</a>.'); ?>

    <div class="row show-grid">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search form-control" style="width: 400px"/>
        </div>
        <div class="col-md-3" style="text-align: right">
            <gims-link-new target='user'></gims-link-new>
        </div>
    </div>

    <gims-grid api="user" options="gridOptions" queryparams="queryParams"></gims-grid>

</div> <!-- /container -->
