<div class="container">

    <h2>
        <ul class="breadcrumb">

            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-history"></i></span>
            <li class="active"><a href="/contribute/activity">Activity</a></li>
        </ul>
    </h2>

    <?php echo $this->helpBox('See who did what recently. Click on a user to see his personal activity.'); ?>
    <gims-activity></gims-activity>

</div> <!-- /container -->