<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-comments"></i></span>
            <li class="active"><a href="/contribute/discussion">Discussions</a></li>
        </ul>
    </h2>

    <?php echo $this->helpBox('See existing discussions and add comment to them. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/discussion.html">detailed documentation</a>.'); ?>

    <div class="row show-grid">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search form-control" style="width: 400px"/>
        </div>
    </div>

    <gims-grid api="discussion" options="gridOptions" queryparams="queryparams"></gims-grid>

</div> <!-- /container -->
