<div class="container">

    <form name="myForm">

        <?php echo $this->crudButtons('survey'); ?>

        <tabs style="margin-top: 20px" active="panes[0].active">
            <pane heading="General info">
                <div class="control-group" ng-class="{error: myForm.code.$invalid}">
                    <label for="survey.code">Code</label>
                    <input id="survey.code" type="text" name="code" ng-model="survey.code" required />
                    <span ng-show="myForm.code.$error.required" class="help-inline">Required</span>
                </div>

                <div class="control-group" ng-class="{error: myForm.name.$invalid}">
                    <label for="survey.name">Name</label>
                    <input id="survey.name" type="text" name="name" ng-model="survey.name" required class="span6" />
                    <span ng-show="myForm.name.$error.required" class="help-inline">Required</span>
                </div>

                <div class="control-group" ng-class="{error: myForm.active.$invalid}">
                    <label for="survey.active">Active</label>
                    <select id="survey.active" name="active" ng-model="survey.active" ng-options="c.value as c.text for c in actives"
                            required></select>
                    <span ng-show="myForm.active.$error.required" class="help-inline">Required</span>
                </div>

                <div class="control-group" ng-class="{error: myForm.year.$invalid}">
                    <label for="survey.year">Year</label>
                    <input id="survey.year" type="number" name="year" ng-model="survey.year" min="1970" max="2100" required />
                    <span ng-show="myForm.year.$error.number" class="help-inline">Not a valid year</span>
                    <span ng-show="myForm.year.$error.required" class="help-inline">Required</span>
                </div>

                <div class="control-group">
                    <label for="survey.comments">Comments</label>
                    <textarea id="survey.comments" type="text" name="comments" ng-model="survey.comments" class="span6"></textarea>
                </div>

                <div class="control-group input-append">

                    <div class="row-fluid">
                        <div class="span6">
                            <label for="survey.dateStart">Date start</label>
                            <input id="survey.dateStart" class="input-small" type="text" ng-model="survey.dateStart" data-date-format="dd/mm/yyyy" bs-datepicker />
                            <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i></button>
                        </div>
                        <div class="span6">
                            <label for="survey.dateEnd">Date end</label>
                            <input id="survey.dateEnd" class="input-small" type="text" ng-model="survey.dateEnd"
                                   data-date-format="dd/mm/yyyy" bs-datepicker/>
                            <button type="button" class="btn" data-toggle="datepicker"><i class="icon-calendar"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </pane>

            <pane heading="Question" active="panes[1].active">

                <div class="row-fluid">
                    <div class="span9">
                        <input type="text" ng-model="filteringText" placeholder="Search..." class="search"
                               style="width: 400px"/>
                    </div>
                    <div class="span3" style="text-align: right">

                        <i class="icon-plus-sign"></i>
                        <link-new-question/>
                    </div>
                </div>
                <div ng-grid="gridQuestions" style="" class="gridStyle" style="height: 100%"></div>
            </pane>

            <pane heading="Questionnaire" active="panes[2].active">
                1234
            </pane>
        </tabs>

        {{ survey | json}}
    </form>

    <?php echo $this->metadata('survey'); ?>
</div> <!-- /container -->
