<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li><a href="/admin/survey">Surveys</a></li>
            <li class="active">{{survey.code}}</li>
        </ul>
    </h2>

    <form name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('survey'); ?>
        <a href='/export/survey/{{survey.id}}/{{survey.name}}.xslx' target='_blank' class='btn btn-default'><i class='fa fa-download'></i> Export all questionnaires</a>

        <tabset style="margin-top: 20px">
            <tab heading="General info" active="tabs[0]" select="selectTab(0)" >

                <div class="form-group" ng-class="{'has-error':myForm.code.$invalid}">
                    <label class="control-label col-sm-1" for="survey.code">Code</label>
                    <div class="col-sm-3">
                        <input id="survey.code" type="text" name="code" ng-model="survey.code" required />
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.code.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.name.$invalid}">
                    <label class="control-label col-sm-1" for="survey.name">Name</label>
                    <div class="col-sm-6">
                        <input id="survey.name" type="text" name="name" ng-model="survey.name" required/>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.name.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.isActive.$invalid}">
                    <label class="control-label col-sm-1" for="survey.isActive">Active</label>
                    <div class="col-sm-2">
                        <select id="survey.isActive" name="active" ng-model="survey.isActive" ng-options="c.value as c.text for c in actives"></select>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.isActive.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.year.$invalid}">
                    <label class="control-label col-sm-1" for="survey.year">Year</label>
                    <div class="col-sm-2">
                        <input id="survey.year" type="number" name="year" ng-model="survey.year" min="1970" max="2100" required />
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.year.$error.number" class="help-block">Not a valid year</span>
                        <span ng-show="myForm.year.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-1" for="survey.comments">Comments</label>
                    <div class="col-sm-6">
                        <textarea id="survey.comments" type="text" name="comments" ng-model="survey.comments"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-1" for="survey.dateStart">Date start</label>
                    <div class="col-md-2">
                        <input id="survey.dateStart" class="input-sm" type="text" ng-model="survey.dateStart" datepicker-popup="dd/MM/yyyy"/>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-1" for="survey.dateEnd">Date end</label>
                    <div class="col-md-2">
                        <input id="survey.dateEnd" class="input-sm" type="text" ng-model="survey.dateEnd" datepicker-popup="dd/MM/yyyy"/>
                    </div>
                </div>
            </tab>

            <tab heading="Questions" active="tabs[1]" select="selectTab(1)" ng-if="survey.id">
                <div gims-grid-question></div>
            </tab>

            <tab heading="Questionnaires" active="tabs[2]" select="selectTab(2)" ng-if="survey.id">
                <div gims-grid-questionnaire></div>
            </tab>

            <tab heading="Users" active="tabs[3]" select="selectTab(3)" ng-if="survey.id">
                <gims-relations relation="UserSurvey" first="survey" second="user" third="role"></gims-relations>
            </tab>
        </tabset>
    </form>

    <?php echo $this->metadata('survey'); ?>
</div> <!-- /container -->
