<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-gims-survey"></i></span>
            <li><a href="/admin/survey">Surveys</a></li>
            <li class="active"> {{survey.code}}</li>
        </ul>
    </h2>

    <?php echo $this->helpBox('Name your survey, create questions and questionnaires and give access to users. For further info, see how to edit the
            <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input.html#survey">survey</a>,
            <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input.html#questions">questions</a> and
            <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input.html#questionnaires">questionnaires</a>.'); ?>


    <form name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('survey'); ?>
        <a href='/export/survey/{{survey.id}}/{{survey.name}}.xslx' target='_blank' class='btn btn-default'><i class='fa fa-download'></i> Export all questionnaires</a>

        <tabset style="margin-top: 20px">
            <tab heading="General" active="tabs[0]" select="selectTab(0)" >

                <div class="form-group" ng-class="{'has-error':myForm.code.$invalid}">
                    <label class="control-label col-sm-1" for="survey.code">Code</label>
                    <div class="col-sm-3">
                        <input id="survey.code" type="text" name="code" ng-model="survey.code" required />
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.code.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{
                        'has-error'
                        : myForm.name.$invalid}">
                    <label class="control-label col-sm-1" for="survey.name">Name</label>
                    <div class="col-sm-6">
                        <input id="survey.name" type="text" name="name" ng-model="survey.name" required/>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.name.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{
                        'has-error'
                        : myForm.isActive.$invalid}">
                    <label class="control-label col-sm-1" for="survey.isActive">Active</label>
                    <div class="col-sm-2">
                        <select id="survey.isActive" name="active" ng-model="survey.isActive" ng-options="c.value as c.text for c in actives"></select>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.isActive.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{
                        'has-error'
                        : myForm.year.$invalid}">
                    <label class="control-label col-sm-1" for="survey.year">Year</label>
                    <div class="col-sm-2">
                        <input id="survey.year" type="number" name="year" ng-model="survey.year" min="1970" max="2100" required />
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.year.$error.number" class="help-block">Not a valid year</span>
                        <span ng-show="myForm.year.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-1" for="survey.comments">Comments</label>
                    <div class="col-sm-6">
                        <textarea id="survey.comments" type="text" name="comments" ng-model="survey.comments"></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-1" for="survey.dateStart">Date start</label>
                    <div class="col-md-2">
                        <span class="input-group">
                            <input id="survey.dateStart" class="input-sm" type="text" ng-model="survey.dateStart" datepicker-popup is-open="dateStartOpened"/>
                            <gims-datepicker-button class="input-group-btn"></gims-datepicker-button>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-1" for="survey.dateEnd">Date end</label>
                    <div class="col-md-2">
                        <span class="input-group">
                            <input id="survey.dateEnd" class="input-sm" type="text" ng-model="survey.dateEnd" datepicker-popup is-open="dateEndOpened"/>
                            <gims-datepicker-button class="input-group-btn"></gims-datepicker-button>
                        </span>
                    </div>
                </div>
            </tab>

            <tab heading="Questions" active="tabs[1]" select="selectTab(1)" ng-if="survey.id">
                <div gims-grid-question></div>
            </tab>

            <tab heading="Questionnaires" active="tabs[2]" select="selectTab(2)" ng-if="survey.id">
                <div gims-grid-questionnaire></div>
            </tab>

            <tab heading="Users" active="tabs[3]" select="selectTab(3)" ng-if="survey.id">
                <gims-relations relation="UserSurvey" properties="['survey', 'user', 'role']"></gims-relations>
            </tab>
        </tabset>
    </form>

    <?php echo $this->metadata('survey'); ?>
</div> <!-- /container -->
