<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li class="active"><a href="/admin/survey">Surveys</a></li>
        </ul>
    </h2>

    <div class="row">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search" style="width: 400px"/>
        </div>
        <div class="col-md-3" style="text-align: right">
            <a class="link-new" href="/admin/survey/new"><i class="icon-plus-sign"></i> new survey</a>
        </div>
    </div>

    <div ng-grid="gridOptions" class="gridStyle"></div>

</div> <!-- /container -->
