<div class="container">

    <h2>
        <ul class="breadcrumb">

            <li class="active"><a href="/admin/survey"><i class="fa fa-gims-survey"></i> Surveys</a></li>

            <button class="btn pull-right" ng-class="{'btn-info':showHelp, 'btn-default':!showHelp}" ng-click="showHelp = !showHelp"><i class='fa fa-question'></i></button>
        </ul>
    </h2>

    <div class="alert alert-info" ng-if="showHelp">
        <p><i class="fa fa-info-circle"></i> Edit an existing survey or create a new one. For further info, see the <a href="http://gims.readthedocs.org/en/develop/content/data_input.html">detailed documentation.</a></p>
    </div>

    <div class="row show-grid">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search" style="width: 400px"/>
        </div>
        <div class="col-md-3" style="text-align: right">
            <gims-link-new target="survey"></gims-link-new>
        </div>
    </div>

    <gims-grid api="survey" options="gridOptions"></gims-grid>

</div> <!-- /container -->
