<div class="modal-header">
    <button type="button" class="close" ng-click="$dismiss()"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title" ng-if="multiple">Select filters</h4>
    <h4 class="modal-title" ng-if="!multiple">Select filter</h4>
</div>

<div class="modal-body">
    <form class="form form-horizontal" role="form">
        <div class="form-group">
            <label for="filterOnName" class="col-sm-2 control-label">Search</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" name="filterOnName" ng-model="data.search" />
            </div>
        </div>
    </form>

    <form class="form form-horizontal" role="form">
        <div class="form-group">
            <label for="filterOnName" class="col-sm-2 control-label">Filters </label>
            <div class="col-md-10"></div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <treecontrol class="tree-classic"
                             tree-model="data.tree"
                             options="data.treeOptions"
                             expanded-nodes="data.expandedNodes"
                             filter-expression="data.search"
                             selected-node="data.selectedNode"
                             on-selection="data.showSelected(node)">

                    <div ng-class="{'selected':node.selected}">
                        <i class="fa fa-gims-filter fa-fw" style="color:{{node.color}};"></i>
                        {{node.name}}
                    </div>
                </treecontrol>
            </div>
        </div>
    </form>

</div>

<div class="modal-footer">
    <button type="button" class="btn btn-default" ng-click="$dismiss()">Close</button>
    <button class="btn btn-primary pull-right" ng-click="data.selectFilters()" ng-disabled="!data.selected.length">Select filters</button>
</div>