language: php
php:
  - "5.5"

addons:
  postgresql: "9.2"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16

before_script:
  - ./bin/install_dependencies.sh configure
  - ./bin/build.sh

script: ./vendor/bin/phing travis
