language: php
php:
  - "5.4"

before_script:
  - ./bin/install_dependencies.sh travis

script: ./vendor/bin/phing test && testacular --version && testacular start config/testacular-e2e.conf.js --no-auto-watch --single-run --browsers PhantomJS --log-level debug
