language: php
php:
  - "5.4"

before_script:
  - ./bin/install_dependencies.sh travis
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

#script: ./vendor/bin/phing test && testacular --version && curl http://gims.local/ && testacular start config/testacular-e2e.conf.js --no-auto-watch --single-run --browsers Firefox --log-level debug
script: cat /etc/apache2/sites-available/default && cat /etc/hosts && dig gims.local && curl http://gims.local/
