<header class="jumbotron">
    <h2>Contribute</h2>
    <p>«Small streams make large rivers»</p>
</header>

<div class="container">

    <!-- Example row of columns -->
    <div class="row">
        <div class="col-sm-6">
            <h2>Data</h2>
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/contribute/jmp">
                        <p><i class="fa fa-gims-questionnaire fa-4x"></i></p>
                        <p>Questionnaires JMP</p>
                    </a>
                </li>
                <li>
                    <a href="/contribute/nsa">
                        <p><i class="fa fa-gims-questionnaire fa-4x"></i></p>
                        <p>Questionnaires NSA</p>
                    </a>
                </li>
                <li>
                    <a href="/contribute/glass">
                        <p><i class="fa fa-gims-questionnaire fa-4x"></i></p>
                        <p>Questionnaires Glass</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-sm-6">
            <h2>Statistics</h2>
            <p>Questionnaires</p>
            <div class="progress">
                <div class="progress-bar" style="width: {{statistics.new / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.new}} / {{statistics.total}} new questionnaires"></div>
                <div class="progress-bar progress-bar-info" style="width: {{statistics.completed / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.completed}} / {{statistics.total}} completed questionnaires"></div>
                <div class="progress-bar progress-bar-warning" style="width: {{statistics.validated / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.validated}} / {{statistics.total}} validated questionnaires"></div>
                <div class="progress-bar progress-bar-success" style="width: {{statistics.published / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.published}} / {{statistics.total}} published questionnaires"></div>
                <div class="progress-bar progress-bar-danger" style="width: {{statistics.rejected / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.rejected}} / {{statistics.total}} rejected questionnaires"></div>
            </div>

            <ul>
                <li>{{statistics.new}} new</li>
                <li>{{statistics.completed}} completed</li>
                <li>{{statistics.validated}} validated</li>
                <li>{{statistics.published}} published</li>
                <li>{{statistics.rejected}} rejected</li>
            </ul>

        </div>
    </div>

</div> <!-- /container -->
