

<!-- Main hero unit for a primary marketing message or call to action -->
<div class="jumbotron">
    <h2>Contribute</h2>
    <p>«Small streams make large rivers»</p>
</div>

<div class="container">

    <!-- Example row of columns -->
    <div class="row">
        <div class="span4">
            <h2>Administration</h2>
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/admin/survey">
                        <p><i class="icon-survey icon-4x"></i></p>
                        <p>Surveys</p>
                    </a>
                </li>
                <li>
                    <a href="/admin/user">
                        <p><i class="icon-user icon-4x"></i></p>
                        <p>Users</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="span4">
            <h2>Data</h2>
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/contribute/questionnaire">
                        <p><i class="icon-questionnaire icon-4x"></i></p>
                        <p>Questionnaires</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="span4">
            <h2>Statistics</h2>
            <p>Questionnaires</p>
            <div class="progress">
                <div class="bar bar-info" style="width: {{statistics.new / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.new}} / {{statistics.total}} new questionnaires"></div>
                <div class="bar bar-warning" style="width: {{statistics.completed / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.completed}} / {{statistics.total}} completed questionnaires"></div>
                <div class="bar bar-success" style="width: {{statistics.validated / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.validated}} / {{statistics.total}} validated questionnaires"></div>
                <div class="bar bar-danger" style="width: {{statistics.rejected / statistics.total * 100}}%;" tooltip-placement="bottom" tooltip="{{statistics.rejected}} / {{statistics.total}} rejected questionnaires"></div>
            </div>

        </div>
    </div>

</div> <!-- /container -->
