<div class="container">

    <style type="text/css">
        input.error {
            border-color: #b94a48 !important;
            color: #b94a48 !important;
            -webkit-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
            -moz-box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        }
    </style>
    <h2>Questionnaire</h2>
    <input ui-select2="availableQuestionnaires" ng-model="selectedQuestionnaire" style="width:100%"
           data-placeholder="Select a questionnaire"/>

    <h2>Questions</h2>

    <div ng-grid="gridOptions" style="height: 300px"></div>
    <div>{{selectedRow}}</div>

</div> <!-- /container -->
