<div class="container">

    <h2>Questionnaire</h2>
    <gims-select api="questionnaire" name="id" model="questionnaire" placeholder="<?php echo $this->translate('Select a questionnaire') ?>" style="width:100%;"/></gims-select>

    <h2>Questions</h2>

    <div class="alert alert-info">Empty values are due to different labels (original denominations) being used in the
        Excel country files for the same
        question of the survey !</div>
    <div ng-grid="gridOptions" class="gridStyle"></div>

    <pre>{{questions | json}}</pre>

</div> <!-- /container -->
