
<gims-questionnaire-tool-bar></gims-questionnaire-tool-bar>

<div class='row-fluid'>
    
    <div class='span4'>
        <gims-questions-nav id='questionnaireNav' nav='hierarchicNavigation' flat-nav='navigation' go-to='goTo(wantedIndex)'></gims-questions-nav>
    </div>

    <div class='span8'>

        <div ng-repeat='parentChapter in parentChapters'>
            <h3>{{parentChapter.name}}</h3>
            <p>{{parentChapter.description}}</p>
            <hr/>
        </div>

        <h3>{{currentQuestion.name}}</h3>
        <p>{{currentQuestion.description}}</p>

        <div ng-switch="currentQuestion.type">
            <div ng-switch-when="Chapter">
                <div ng-repeat='child in currentQuestionChildren'>
                    <h4>{{child.name}}</h4>

                    <div class='row-fluid'>
                        <div ng-switch="child.type" >
                            <div ng-switch-when="Chapter">
                                <p>{{child.description}}</p>
                            </div>
                            <div ng-switch-when="Numeric">
                                <gims-num-question question='child' index="index"></gims-num-question>
                            </div>
                            <div ng-switch-when="Text">
                                <gims-text-question question='child' index="index"></gims-text-question>
                            </div>
                            <div ng-switch-when="Choice">
                                <gims-choi-question question='child' index="index"></gims-choi-question>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            <div ng-switch-when="Numeric" class='row-fluid'>
                <gims-num-question question='currentQuestion' index="index"></gims-num-question>
            </div>

            <div ng-switch-when="Text">
                <gims-text-question question='currentQuestion' index="index"></gims-text-question>
            </div>

            <div ng-switch-when="Choice">
                <gims-choi-question question='currentQuestion' index="index"></gims-choi-question>
            </div>

        </div>
        
        <!--pre>{{index|json}}</pre-->
    </div>
</div>
<br/>
<gims-questionnaire-tool-bar></gims-questionnaire-tool-bar>