<gims-rule-text-field-panel refresh="refresh(questionnairesPermissions, filtersComputing, questionnairesUsages)" readonly="!mode.isContribute"></gims-rule-text-field-panel>

<div class="container" >
    <!-- Toolbar -->
    <div class="navbar navbar-default hidden-print">
        <a class="navbar-brand" href="#">{{mode.name}} filters</a>

        <form class="navbar-form">
            <!-- Back button, if return URL is specified -->
            <button class="btn btn-default" ng-if="returnUrl" ng-click="cancel();"><i class="fa fa-gims-back"></i> Back</button>

            <!-- Save all the new questionnaires -->
            <button class="btn btn-primary" ng-if="isEmptyQuestionnaires() || isEmptyFilters()" ng-click="saveAll();" ng-disabled="isLoading || !tabs.filters && !tabs.questionnaires"><i class="fa fa-save"></i> Save new elements</button>

            <!-- Clear the selection -->
            <a href class="btn btn-default" ng-click="tabs.questionnaires=[];tabs.filters=[];tabs.filterSet=null;tabs.country=null;tabs.filter=null;tabs.survey=null"><i class="fa fa-eraser"></i> Clear selection</a>

            <!-- Hide/Show selection tools and/or children filters -->
            <button class="btn btn-default" ng-click="expandSelection = !expandSelection"><i class="fa" ng-class="{'fa-compress':expandSelection,'fa-expand text-primary':!expandSelection}"></i> Selection</button>

            <?php echo $this->helpButton(); ?>
        </form>
    </div>

    <div ng-switch="mode.name">
        <div ng-switch-when="Browse">
            <?php echo $this->helpBox('Select a country and filter set and view the corresponding data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_processing.html">detailed documentation</a>.'); ?>
        </div>
        <div ng-switch-when="Contribute JMP">
            <?php echo $this->helpBox('Select questionnaires and filters and edit existing or new data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input2.html#di-jmp">detailed documentation</a>.'); ?>
        </div>
        <div ng-switch-when="Contribute NSA">
            <?php echo $this->helpBox('Select an existing NSA filter set or create one and edit existing or new data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input2.html#di-nsa">detailed documentation</a>.'); ?>
        </div>
    </div>
    <!-- Selection panel for filters and questionnaires -->
    <form name="selectionForm">
        <div class="row show-grid ng-trans ng-trans-slide-up" ng-show="expandSelection" >

            <!-- Filter selection -->
            <div class="col-md-6" ng-show="(tabs.questionnaires.length || mode.isContribute) && !mode.isSector">
                <div class="row" ng-class="{'has-error':!tabs.filters.length}">
                    <div class="col-md-12">
                        <h3 class="control-label">Filter (rows) <small ng-if="!tabs.filters.length">(Required)</small></h3>
                    </div>

                    <div class="col-md-12">
                        <tabset>
                            <tab heading="Filter set" >
                                <gims-select
                                    model="tabs.filterSet"
                                    api="filterSet"
                                    placeholder="Select filter set"
                                    disabled="isLoading"
                                    style="width: 100%">
                                </gims-select>
                            </tab>
                            <tab heading="Filter's children">
                                <gims-filter
                                        model="tabs.filter"
                                        name="filter"
                                        show-selection-path="true"
                                        disabled="isLoading">
                                </gims-filter>
                            </tab>
                            <tab heading="Filters ({{tabs.filters.length}})">
                                <gims-filter
                                        model="tabs.filters"
                                        name="filters"
                                        query-params="filterFields"
                                        show-selection-path="true"
                                        disabled="isLoading"
                                        multiple>
                                </gims-filter>
                            </tab>
                        </tabset>
                    </div>
                </div>
            </div>

            <!-- Questionnaires selection -->
            <div class="col-md-6">
                <div class="row" ng-class="{'has-error':!tabs.questionnaires.length && !mode.isContribute}">

                    <div>
                        <div class="col-md-12">
                            <h3 class="control-label" ng-if="!mode.isSector">Questionnaires (columns) <small ng-if="!tabs.questionnaires.length && !mode.isContribute">(Required)</small></h3>
                        </div>

                        <div class="col-md-12">
                            <tabset>
                                <tab heading="Country">
                                    <gims-select
                                            model="tabs.country"
                                            api="country"
                                            queryparams="countryParams"
                                            placeholder="Select a country"
                                            change-url="mode.isSector"
                                            disabled="isLoading"
                                            style="width: 100%">
                                    </gims-select>
                                </tab>
                                <tab heading="Survey" ng-if="!mode.isSector">
                                    <gims-select
                                        model="tabs.survey"
                                        api="survey"
                                        placeholder="Select survey"
                                        search-attributes="code,name"
                                        custom-selection-template="{{surveysTemplate}}"
                                        custom-result-template="{{surveysTemplate}}"
                                        change-url="false"
                                        disabled="isLoading"
                                        style="width: 100%">
                                    </gims-select>
                                </tab>
                                <tab heading="Questionnaires ({{tabs.questionnaires.length}})" ng-if="!mode.isSector">
                                    <gims-select
                                            model="tabs.questionnaires"
                                            name="questionnaires"
                                            api="questionnaire"
                                            queryparams="questionnaireParams"
                                            placeholder="Select questionnaires"
                                            disabled="isLoading"
                                            multiple
                                            style="width: 100%">
                                    </gims-select>
                                </tab>
                                <tab ng-if="tabs.glass.length">
                                    <tab-heading><span class="text-warning"><i class="fa fa-exclamation-triangle" ></i> Others</span></tab-heading>
                                    <p>Some selected surveys are only available in advanced edition mode and one at a time.</p>
                                    <p>Click to edit.</p>
                                    <ul class="list-unstyled">
                                        <li ng-repeat="q in tabs.glass"><a href="/contribute/glaas/{{q.id}}?returnUrl={{currentUrl}}"><i class="fa fa-external-link"></i> {{q.name}}</a></li>
                                    </ul>
                                </tab>
                            </tabset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <div class="alert alert-danger" ng-show="mode.isSector && !NSAStructureOk && tabs.filter">
        <span class=alert-link>NSA filter structure error</span>

        <p>You're on NSA view and filter structure is not compatible.</p>
        <p>The structure must have a single root filter with some equipments. Each equipment, must have two children.</p>
        <br/>
        <ul>
            <li><span class=alert-link>Country sector</span>
                <ul>
                    <li>Equipment 1
                        <ul>
                            <li>Number of equipments</li>
                            <li>Number of persons by equipment</li>
                        </ul>
                    </li>
                    <li>Equipment 2
                        <ul>
                            <li>Number of equipments</li>
                            <li>Number of persons by equipment</li>
                        </ul>
                    </li>
                    <li>Equipment 3
                        <ul>
                            <li>Number of equipments</li>
                            <li>Number of persons by equipment</li>
                        </ul>
                    </li>
                    <li>Equipment 4
                        <ul>
                            <li>Number of equipments</li>
                            <li>Number of persons by equipment</li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>

    </div>

    <!-- Tabs parts -->
    <tabset class="nav-tabs-centered" ng-show="(mode.isSector && tabs.filter) || tabs.filters.length && (tabs.questionnaires.length || mode.isContribute)">
        <tab ng-repeat="part in parts" heading="{{part.name}}" select="tabs.part = part"></tab>
    </tabset>

</div>



<!-- Table of filters, questionnaires and answers. Display in full width when there are too much elements -->
<div ng-show="(mode.isSector && tabs.filter) || tabs.filters.length && (tabs.questionnaires.length || mode.isContribute)" class="container gims-full-width-container">

    <div class="row">
        <div class="col-md-12">
            <form name="answersForm" novalidate>
                <table class="table table-bordered table-condensed bigtable">

                    <!-- Head part : including country, survey code and survey year -->
                    <tbody>

                        <!-- Action buttons (first row) -->
                        <tr>
                            <!-- Add a new empty questionnaire -->
                            <td style="width:350px">
                                <a class="btn btn-default btn-sm"
                                   ng-click="addQuestionnaire();"
                                   ng-if="mode.isContribute">
                                    <i class="fa fa-plus-circle"></i> Add new questionnaire
                                </a>
                            </td>

                            <td ng-repeat="questionnaire in tabs.questionnaires track by $index" ng-class="{'showLabels': questionnaire.showLabels}">

                                <!-- Display errors on questionnaires / surveys integrity data structure (like two different years for the same survey or two countries for the same survey -->
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.duplicateCountryCode" tooltip="Surveys may not have the same country more than once" tooltip-placement="left"><i class="fa fa-warning"></i></a>
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.codeAndYearDifferent" tooltip="Surveys with the same code may have the same year" tooltip-placement="left"><i class="fa fa-warning"></i></a>
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.countryAlreadyUsedForExistingSurvey" tooltip="This country is already assigned to a survey with the same code" tooltip-placement="left"><i class="fa fa-warning"></i></a>
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.surveyExistWithDifferentYear" tooltip="This survey already exists with different year : {{questionnaire.survey.existingYear}}" tooltip-placement="left"><i class="fa fa-warning"></i></a>

                                <!-- mark new questionnaire / is loading -->
                                <a class="btn btn-sm" ng-if="!questionnaire.id || questionnaire.isLoading" tooltip="New survey" tooltip-placement="left" ><i class="fa fa-lg" ng-class="{'fa-asterisk':!questionnaire.isLoading, 'fa-gims-loading':questionnaire.isLoading}"></i></a>

                                <div class="btn-group pull-right">
                                    <button type="button" class="btn btn-default dropdown-toggle btn-sm" data-toggle="dropdown">
                                        <i class="fa fa-angle-down"></i>
                                    </button>
                                    <ul class="dropdown-menu pull-right" role="menu">

                                        <!-- Save a single questionnaire -->
                                        <li>
                                            <a ng-click="saveAll(questionnaire)"
                                               ng-if="mode.isContribute && !questionnaire.id"
                                               ng-class="{'disabled' : !checkIfSavableQuestionnaire(questionnaire)}" href>
                                                <span class="text-primary"><i class="fa fa-fw fa-save"></i> Save this survey</span>
                                            </a>
                                        </li>

                                        <li><a href ng-click="removeQuestionnaire($index)"><i class="fa fa-times fa-fw"></i> Hide this column</a></li>

                                        <li class="divider"></li>

                                        <li ng-if="questionnairesWithUsages.length && !questionnaire.filterQuestionnaireUsages.length" class="dropdown-header">Status</li>
                                        <li><a><i class="fa fa-fw fa-flag"></i> {{questionnaire.status|capital}}</a></li>

                                        <li class="divider" ng-if='mode.isContribute'></li>

                                        <!-- Questions labels edition button, display an additionnal column -->
                                        <li ng-if='mode.isContribute'>
                                            <a ng-click="questionnaire.showLabels = true" href>
                                                <i class="fa fa-question fa-fw"></i>
                                                Edit question labels
                                            </a>
                                        </li>

                                        <!-- Edit questionnaire comment, display an additionnal column -->
                                        <li ng-if='mode.isContribute'>
                                            <a ng-click="tabs.selectedQuestionnaireForComments = questionnaire;" href>
                                                <i class="fa fa-comment fa-fw"></i>
                                                Edit survey comments
                                            </a>
                                        </li>

                                        <!-- Duplicate rules -->
                                        <!-- Disabled for the moment, because add buttons that are not required since the news NSA view has been added, but works -->
                                        <!--<li ng-if="questionnairesWithUsages.length && !questionnaire.filterQuestionnaireUsages.length" class="divider"></li>-->
                                        <!--<li ng-if="questionnairesWithUsages.length && !questionnaire.filterQuestionnaireUsages.length" class="dropdown-header">Suggested formulas</li>-->
                                        <!--<li ng-repeat="q in questionnairesWithUsages"-->
                                            <!--ng-if="q.id && (!questionnaire.filterQuestionnaireUsages || !questionnaire.filterQuestionnaireUsages.length)"-->
                                            <!--ng-attr-tooltip="{{!questionnaire.id && 'When the survey is saved, click here to report the same formulas'}}"-->
                                            <!--tooltip-placement="left">-->
                                            <!--<a href ng-click="copyFilterUsages(questionnaire, q)"><i class="fa fa-gims-questionnaire fa-fw" ng-class="{'disabled':!questionnaire.id}"></i> {{q.geoname.country.name}} - {{q.survey.name}}</a>-->
                                        <!--</li>-->

                                        <li ng-if="mode.isContribute && questionnaire.id" class="divider"></li>

                                        <!-- Links to admin -->
                                        <li ng-if="mode.isContribute && questionnaire.id" class="dropdown-header">
                                            Links to admin section
                                        </li>

                                        <li  ng-if="mode.isContribute && questionnaire.survey.id">
                                            <a href="/admin/survey/edit/{{questionnaire.survey.id}}?returnUrl={{currentUrl}}">
                                                <i class="fa fa-gims-survey fa-fw"></i>
                                                Edit Survey
                                            </a>
                                        </li>

                                        <!-- Link to questionnaire in /admin/ section -->
                                        <li ng-if="mode.isContribute && questionnaire.id">
                                            <a  href="/admin/questionnaire/edit/{{questionnaire.id}}?returnUrl={{currentUrl}}">
                                                <i class="fa fa-gims-questionnaire fa-fw"></i>
                                                Edit Questionnnaire
                                            </a>
                                        </li>


                                    </ul>
                                </div>
                            </td>
                        </tr>

                        <!-- Questionnaire's geoname row-->
                        <tr class="active" ng-if="tabs.questionnaires.length">
                            <td></td>
                            <td ng-if="tabs.selectedQuestionnaireForLabels" class="text-center">{{tabs.selectedQuestionnaireForLabels.geoname.country.name}} </td>
                            <td ng-repeat="questionnaire in tabs.questionnaires track by $index">
                                <div ng-switch="!!questionnaire.id">
                                    <div ng-switch-when="true" class="text-center">
                                        <div name="questionnaireForm" class="input-group input-group-sm">
                                            <div class="input-group-addon"><i class="fa fa-fw fa-gims-questionnaire"></i></div>
                                            <input ng-disabled="true" type="text" class="text-center" placeholder="Country" ng-model="questionnaire.geoname.country.name" name="country" />
                                        </div>
                                    </div>
                                    <div ng-switch-when="false" class="has-error">
                                        <ng-form name="questionnaireForm">
                                            <gims-select
                                                required
                                                disabled="mode.isSector || questionnaire.id || questionnaire.isLoading"
                                                api="country" model="questionnaire.geoname.country"
                                                queryparams="countryParams"
                                                placeholder="Country"
                                                change-url="false"
                                                style="width: 100%"
                                                ng-change="checkQuestionnairesIntegrity();completeQuestionnaire(questionnaire);">
                                            </gims-select>
                                            {{mode.isSector}}
                                        </ng-form>
                                    </div>
                                </div>
                            </td>
                        </tr>

                        <!-- Survey's code row -->
                        <tr class="active" ng-if="tabs.questionnaires.length">
                            <td></td>
                            <td ng-if="tabs.selectedQuestionnaireForLabels" class="text-center">{{tabs.selectedQuestionnaireForLabels.survey.code}}</td>
                            <td ng-repeat="questionnaire in tabs.questionnaires track by $index" class="text-center">
                                <ng-form name="questionnaireForm" class="input-group input-group-sm" ng-class="{'has-error':questionnaireForm.code.$invalid}">
                                    <div class="input-group-addon"><i class="fa fa-fw fa-gims-survey"></i></div>
                                    <input ng-disabled="questionnaire.survey.id || questionnaire.isLoading" type="text" class="text-center" placeholder="Code" ng-model="questionnaire.survey.code" name="code" required ng-class="{'error':questionnaire.errors.duplicateCountryCode || questionnaire.errors.codeAndYearDifferent || questionnaireForm.code.$invalid}" ng-blur="checkQuestionnairesIntegrity();completeQuestionnaire(questionnaire);"/>
                                </ng-form>
                            </td>
                        </tr>

                        <!-- Survey's year row -->
                        <tr class="active" ng-if="tabs.questionnaires.length">
                            <td>
                                <button class="btn btn-default btn-sm" ng-show="!mode.isSector" ng-click="setExpandHierarchy(!expandHierarchy)"><i class="fa" ng-class="{'fa-compress':expandHierarchy,'fa-expand':!expandHierarchy}"></i> Filter hierarchy tree</button>
                                <button class="btn btn-default btn-sm pull-right" ng-show="tabs.questionnaires.length > 1 && !questionnairesAreSorted" ng-click="orderQuestionnaires(false)"><i class="fa fa-sort-amount-asc fa-rotate-270"></i> Sort by year</button>
                            </td>
                            <td ng-if="tabs.selectedQuestionnaireForLabels" class="text-center">{{tabs.selectedQuestionnaireForLabels.survey.year}}</td>
                            <td ng-repeat="questionnaire in tabs.questionnaires track by $index">
                                <ng-form name="questionnaireForm" class="input-group input-group-sm" ng-class="{'has-error':questionnaireForm.year.$invalid}">
                                    <div class="input-group-addon"><i class="fa fa-fw fa-gims-survey"></i></div>
                                    <input ng-disabled="questionnaire.survey.id || questionnaire.isLoading" type="number" class="text-center" placeholder="Year" ng-model="questionnaire.survey.year" name="year" min="1980" max="2015" size="4" required ng-class="{'error': questionnaire.errors.codeAndYearDifferent || questionnaireForm.year.$invalid}" ng-blur="checkQuestionnairesIntegrity();completeQuestionnaire(questionnaire);"/>
                               </ng-form>
                           </td>
                        </tr>

                        <!-- Population row -->
                        <tr class="active" ng-if="tabs.questionnaires.length && mode.isSector">
                            <td>
                                <button class="btn btn-default btn-sm" ng-show="!mode.isSector" ng-click="setExpandHierarchy(!expandHierarchy)"><i class="fa" ng-class="{'fa-compress':expandHierarchy,'fa-expand':!expandHierarchy}"></i> Filter hierarchy tree</button>
                            </td>
                            <td ng-if="tabs.selectedQuestionnaireForLabels"></td>
                            <td class="text-center" ng-repeat="questionnaire in tabs.questionnaires track by $index">
                                <ng-form name="valueForm" class="input-group input-group-sm" ng-class="{'has-error':valueForm.value.$invalid}" tooltip="Leave empty to use official population data">
                                    <div class="input-group-addon"><i class="fa fa-fw" ng-class="{'fa-gims-population':!questionnaire.populations[tabs.part.id].isLoading,'fa-gims-loading':questionnaire.populations[tabs.part.id].isLoading}"></i></div>
                                    <input  type="number"
                                            class="text-center"
                                            placeholder="Population"
                                            min="0"
                                            name="value"
                                            ng-focus="setInitialValue(questionnaire.populations[tabs.part.id], questionnaire.populations[tabs.part.id].population)"
                                            ng-blur="savePopulation(questionnaire, questionnaire.populations[tabs.part.id])"
                                            ng-model="questionnaire.populations[tabs.part.id].population"
                                            ng-disabled="questionnaire.isLoading"
                                            />
                                </ng-form>
                            </td>
                        </tr>

                    </tbody>
                    <!-- End of table header-->

                    <!-- Label for questionnaire comments and close btn -->
                    <tbody ng-if="tabs.selectedQuestionnaireForComments">
                        <tr>
                            <td>
                                <a class="btn btn-default btn-xs" ng-click="tabs.selectedQuestionnaireForComments = null"><i class="fa fa-times"></i></a>
                                <i class="fa fa-comment"></i> Comments for {{tabs.selectedQuestionnaireForComments.geoname.country.name}}, {{tabs.selectedQuestionnaireForComments.survey.code}}, {{tabs.selectedQuestionnaireForComments.survey.year}}
                            </td>

                            <td ng-attr-colspan="{{!tabs.selectedQuestionnaireForLabels && tabs.questionnaires.length || tabs.selectedQuestionnaireForLabels && (tabs.questionnaires.length+1)}}" ng-if="tabs.selectedQuestionnaireForComments" class="text-center">

                                <ng-form name="labelForm" ng-if="mode.isContribute">
                                    <div class="input-group input-group-sm">
                                        <span class="input-group-addon"><i class="fa fa-comment"></i></span>
                                        <textarea class="form-control"
                                               ng-model="tabs.selectedQuestionnaireForComments.comments"
                                               ng-focus="tabs.selectedQuestionnaireForComments.initialComments = tabs.selectedQuestionnaireForComments.comments"
                                               ng-blur="saveComment(tabs.selectedQuestionnaireForComments)"
                                               name="label">
                                        </textarea>
                                    </div>
                                </ng-form>
                            </td>
                        </tr>
                    </tbody>

                    <tbody>
                        <!-- Filters and answers rows -->
                        <tr ng-repeat="filter in tabs.filters track by $index" ng-if="(mode.isSector && isValidId(filter)) || expandHierarchy || filter.level <= tabs.filters[0].level" ng-class="{'active':mode.isSector && filter.level < 2}"  ng-mouseenter="filter.hover=true" ng-mouseleave="filter.hover=false">

                            <!-- Filter name column-->
                            <td>
                                <span class="btn btn-default btn-xs" style="vertical-align:top;" ng-click="removeFilter(filter)" ng-class="{'invisible':!mode.isContribute || !(!mode.isSector || mode.isSector && filter.level <= 1) || !filter.hover}" tooltip="Hide this row and its children" tooltip-placement="right"><i class="fa fa-times"></i></span>

                                <span ng-if="isValidId(filter) || mode.isSector && filter.level != 1" ng-class="{'strong':filter.level == tabs.filters[0].level && !filter.sectorChild}" style="margin-left:{{(filter.level - tabs.filters[0].level) * 2}}em;">
                                    <i class="fa" style="color:{{filter.color}}" ng-class="{'fa-gims-filter':!filter.isLoading && isValidId(filter), 'fa-asterisk text-primary':!filter.isLoading && !isValidId(filter), 'fa-gims-loading':filter.isLoading}"></i>
                                    {{filter.name}}
                                    <a href="/admin/filter/edit/{{filter.id}}?returnUrl={{currentUrl}}" ng-if="mode.isContribute && !filter.sectorChild && filter.hover"><i class="fa fa-pencil"></i></a>
                                </span>
                                <div ng-if="!isValidId(filter) && mode.isSector && filter.level == 1" style="display:inline-block;vertical-align:top;width:80%;margin-left:{{(filter.level - tabs.filters[0].level) * 2}}em;">
                                    <ng-form name="filterName" class="input-group" ng-class="{'has-error':filterName.$invalid}">
                                        <span class="input-group-addon"><i class="fa" ng-class="{'fa-asterisk':!filter.isLoading,'fa-gims-loading':filter.isLoading,'text-primary':!filterName.$invalid}"></i></span>
                                        <input type="text" name="name" ng-model="filter.name" placeholder="Facility name" required />
                                    </ng-form>
                                </div>
                            </td>

                            <!-- Questionnaires columns -->
                            <td ng-repeat="questionnaire in tabs.questionnaires track by $index">
                                <div class="row">
                                    <div class="col-md-8" ng-if="questionnaire.showLabels">
                                        <ng-form name="labelForm">
                                            <div class="input-group input-group-sm">
                                                <span class="input-group-addon"><i class="fa" ng-class="{'fa-question':!tabs.selectedQuestionnaireForLabels.survey.questions[filter.id].isLoading,'fa-gims-loading':tabs.selectedQuestionnaireForLabels.survey.questions[filter.id].isLoading}"></i></span>
                                                <input class="form-control"
                                                       ng-model="questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id]"
                                                       ng-blur="saveQuestion(questionnaire.survey.questions[filter.id], questionnaire)"
                                                       name="label"
                                                       ng-required="questionnaire.survey.questions[filter.id].answers[part.id][questionnaire.survey.questions[filter.id].value]"
                                                       ng-class="{'error': labelForm.label.$invalid}"/>
                                            </div>
                                        </ng-form>
                                    </div>
                                    <div ng-class="{'col-md-4': questionnaire.showLabels, 'col-md-12' : !questionnaire.showLabels}">

                                        <!-- Display answers / formulas in *contribute* mode -->
                                        <ng-form name="valueForm" ng-if="!mode.isSector || filter.level > 0">
                                            <div class="input-group input-group-sm">
                                                <!-- add-on buttons on input fields -->
                                                 <span class="input-group-btn">
                                                    <button type="button" class="btn btn-default dropdown-toggle"  data-toggle="dropdown-menu" ng-if="questionnairesStatus[questionnaire.status] || questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id] && isValidNumber(questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value]) || questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].second || questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].first || questionnaire.survey.questions[filter.id].answers[tabs.part.id].isLoading">
                                                        <span ng-switch="getCellType(questionnaire, filter, tabs.part.id)">
                                                            <i ng-switch-when="loading" class="fa fa-fw fa-gims-loading"></i>
                                                            <i ng-switch-when="error" class="fa fa-fw fa-warning text-warning"></i>
                                                            <i ng-switch-when="answer" class="fa fa-fw fa-question" tooltip="manually answered"></i>
                                                            <i ng-switch-when="rule" class="fa fa-fw fa-gims-rule" tooltip="computed with rules" ng-class="{'text-primary':isComputing}"></i>
                                                            <i ng-switch-when="summand" class="fa fa-fw fa-gims-summand" tooltip="computed with summands" ng-class="{'text-primary':isComputing}"></i>
                                                            <i ng-switch-when="child" class="fa fa-fw fa-gims-child"  tooltip="computed with children" ng-class="{'text-primary':isComputing}"></i>
                                                            <i ng-switch-default class="fa fa-fw fa-angle-down"></i>
                                                        </span>
                                                    </button>

                                                     <!-- drop down menu -->
                                                    <ul class="dropdown-menu pull-right" ng-if="questionnairesStatus[questionnaire.status] || questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id] || questionnaire.survey.questions[filter.id].answers[tabs.part.id].id || questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][tabs.part.id]">
                                                        <li ng-if="questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id] || questionnaire.survey.questions[filter.id].answers[tabs.part.id].id" class="dropdown-header">Information</li>
                                                        <li ng-if="questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id]">
                                                            <a><i class="fa fa-question fa-fw"></i> {{questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id]}}</a>
                                                        </li>
                                                        <li ng-if="isValidNumber(questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value])" >
                                                            <a><i class="fa fa-crosshairs fa-fw"></i> Exact value: {{questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value]}}</a>
                                                        </li>
                                                        <li ng-if="questionnaire.survey.questions[filter.id].answers[tabs.part.id].error">
                                                            <a><i class="fa fa-warning text-warning"></i> This answer has not been saved.</a>
                                                        </li>

                                                        <!-- Rules -->
                                                        <li ng-if="((mode.isContribute && questionnairesStatus[questionnaire.status]) || questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][tabs.part.id].length) && (questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id] || questionnaire.survey.questions[filter.id].answers[tabs.part.id].id)" class="divider"></li>
                                                        <li ng-if="(mode.isContribute && questionnairesStatus[questionnaire.status]) || questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][tabs.part.id].length" class="dropdown-header">Rules used for computation</li>
                                                        <li ng-repeat="usage in questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][tabs.part.id]">
                                                            <a href gims-select-usage="usage"><i class="fa fa-gims-rule fa-fw"></i> {{usage.rule.name}}</a> <!--href="/admin/rule/edit/{{usage.rule.id}}"-->
                                                        </li>

                                                        <li ng-if="mode.isContribute && questionnairesStatus[questionnaire.status]">
                                                            <a href gims-add-usage questionnaire="questionnaire" filter="filter" part="tabs.part"><i class="fa fa-plus-circle fa-fw"></i> Add a rule</a>
                                                        </li>

                                                        <!-- Summands -->
                                                        <li ng-if="filter.summands.length" class="divider"></li>
                                                        <li ng-if="filter.summands.length" class="dropdown-header">Summands used for computation</li>
                                                        <li ng-repeat="summand in filter.summands">
                                                            <a href="/admin/filter/edit/{{summand.id}}"><i class="fa fa-gims-filter fa-fw"></i> {{filter.name}}</a>
                                                        </li>

                                                        <!--<li ng-if="!isValidNumber(questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value]) && isValidNumber(questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].second)"><a><i class="fa fa-cog fa-fw"></i></a></li>-->
                                                        <li ng-if="questionnairesStatus[questionnaire.status] && (filter.summands.length || ((mode.isContribute && questionnairesStatus[questionnaire.status]) || questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][tabs.part.id].length) || questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id])" class="divider"></li>
                                                        <li ng-if="questionnairesStatus[questionnaire.status]" class="dropdown-header">Actions</li>
                                                        <li ng-if="questionnairesStatus[questionnaire.status]">
                                                            <a href ng-click="toggleExcludeRule(questionnaire, filter.id, tabs.part.id)"><i class="fa fa-gims-rule fa-fw"></i> {{excludeRuleExists(questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][tabs.part.id]) ? 'Include in further computing' : 'Exclude from further computing'}}</a>
                                                        </li>
                                                        <li ng-if="questionnairesStatus[questionnaire.status]">
                                                            <a href ng-if="questionnaire.survey.questions[filter.id].isAbsolute" ng-click="toggleQuestionAbsolute(questionnaire, questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[tabs.part.id])"><i class="fa fa-fw">%</i> Set question as percent value</a>
                                                            <a href ng-if="!questionnaire.survey.questions[filter.id].isAbsolute" ng-click="toggleQuestionAbsolute(questionnaire, questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[tabs.part.id])"><i class="fa fa-fw fa-plus-square-o"></i> Set question as absolute value</a>
                                                        </li>
                                                        <li ng-if="questionnairesStatus[questionnaire.status] && questionnaire.survey.questions[filter.id].answers[tabs.part.id].id">
                                                            <a href ng-click="removeAnswer(questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[tabs.part.id])">
                                                                <span class="text-danger"><i class="fa fa-trash-o fa-fw"></i> Remove answer</span>
                                                            </a>
                                                        </li>
                                                    </ul>
                                                </span>

                                                <!-- input for edit answer -->
                                                <input ng-if="questionnaire.survey.questions[filter.id].value"
                                                       class="form-control text-center"
                                                       ng-class="{'error': valueForm.value.$invalid, 'excluded-from-computing': !isValidNumber(questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].second) && isValidNumber(questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].first)}"
                                                       name="value"
                                                       type="number"
                                                       min="0"
                                                       gims-select-token part="tabs.part" questionnaire="questionnaire" filter="filter"
                                                       ng-max="questionnaire.survey.questions[filter.id].max"
                                                       percent="{{questionnaire.survey.questions[filter.id].isAbsolute}}"
                                                       percent-placeholder="{{questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].second || questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].first}}"
                                                       question="questionnaire.survey.questions[filter.id]"
                                                       ng-focus="initQuestionAbsolute(questionnaire.survey.questions[filter.id]);setAnswerInitialValue(questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[tabs.part.id]); getPermissions(questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[tabs.part.id])"
                                                       ng-blur="saveAnswer(questionnaire.survey.questions[filter.id].answers[tabs.part.id], questionnaire.survey.questions[filter.id], filter, questionnaire, tabs.part)"
                                                       ng-model="questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value]"
                                                       ng-readonly="!questionnairesStatus[questionnaire.status] ||
                                                                    questionnaire.survey.questions[filter.id].answers[tabs.part.id].permissions.update === false ||
                                                                    mode.isSector && filter.level <= 1 ||
                                                                    !mode.isContribute"
                                                        />

                                                <span class="input-group-addon" ng-if="!isValidNumber(questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value]) && (!!questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].second || !!questionnaire.survey.questions[filter.id].filter.values[tabs.part.id].first)" tooltip="Percent value (between 0 and 100)" tooltip-placement="left"><i class="fa fa-fw">%</i></span>
                                                <span class="input-group-addon" ng-if="questionnaire.survey.questions[filter.id].isAbsolute === false && isValidNumber(questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value])" tooltip="Percent value (between 0 and 100)" tooltip-placement="left"><i class="fa fa-fw">%</i></span>
                                                <span class="input-group-addon" ng-if="questionnaire.survey.questions[filter.id].isAbsolute === true  && isValidNumber(questionnaire.survey.questions[filter.id].answers[tabs.part.id][questionnaire.survey.questions[filter.id].value])" tooltip="Positive number" tooltip-placement="left"><i class="fa fa-plus-square-o fa-fw"></i></span>
                                            </div>
                                        </ng-form>
                                        <!--<pre>{{questionnaire.survey.questions[filter.id]|json}}</pre>-->
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr ng-if="!mode.isSector">
                            <td  colspan="{{tabs.questionnaires.length + 1}}">
                                <a href ng-click="toggleShowQuestionnaireUsages()">
                                   <span ng-if="!showQuestionnaireUsages">Show Calculations / Estimations / Ratios</span>
                                   <span ng-if="showQuestionnaireUsages">Hide Calculations / Estimations / Ratios</span>
                                </a>
                            </td>
                        </tr>
                        <tr ng-if="showQuestionnaireUsages" ng-repeat="rule in questionnaireUsages[tabs.part.id] track by $index">

                            <!-- QuestionnaireUsage's rule name column-->
                            <td>
                                <i class="fa fa-gims-rule"></i> {{rule.name}}
                            </td>

                            <!-- QuestionnaireUsage's value name column -->
                            <td ng-repeat="questionnaire in tabs.questionnaires track by $index" style="text-align: center;" >
                                <span ng-if="rule.values[questionnaire.id]" gims-select-token part="tabs.part" questionnaire="questionnaire" rule="rule.values[questionnaire.id]">
                                    <a href><i class="fa fa-pencil" tooltip="Edit rule"></i></a><!--="/admin/rule/edit/{{rule.values[questionnaire.id].id}}"-->
                                    {{rule.values[questionnaire.id].value}}
                                </span>
                            </td>
                        </tr>
                        <tr ng-if="mode.isSector">
                            <td  colspan="{{tabs.questionnaires.length + 1}}">
                                <a class="btn btn-default btn-sm"
                                   ng-click="addEquipment();"
                                   ng-class="{'disabled': getFiltersByLevel(0).length != 1}">
                                    <i class="fa fa-plus-circle"></i> Add new facility
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </form>
        </div>
    </div>
</div>
