<div disable-animate class="container">
    <!-- Toolbar -->
    <div class="navbar navbar-default hidden-print">
        <a class="navbar-brand" href="#">{{data.mode.name}} filters</a>

        <form class="navbar-form">
            <!-- Back button, if return URL is specified -->
            <button class="btn btn-default" ng-if="returnUrl" ng-click="cancel();"><i class="fa fa-gims-back"></i> Back</button>

            <!-- Save all the new questionnaires -->
            <button class="btn btn-primary" ng-if="hasUnsavedElement()" ng-click="saveAll();" ng-disabled="isLoading || !data.filters && !data.questionnaires"><i class="fa fa-save"></i> Save new elements</button>

            <!-- Clear the selection -->
            <a href class="btn btn-default" ng-click="data.questionnaires = []; data.filters = []; data.filterSet = null; data.country = null; data.filter = null; data.survey = null"><i class="fa fa-eraser"></i> Clear selection</a>

            <!-- Hide/Show selection tools and/or children filters -->
            <button class="btn btn-default" ng-click="expandSelection = !expandSelection"><i class="fa" ng-class="{'fa-compress':expandSelection,'fa-expand text-primary':!expandSelection}"></i> Selection</button>

            <!-- Show all original nominations -->
            <button class="btn btn-default" ng-click="toggleOriginalDenominations()"><i class="fa fa-question"></i> Show/Hide question labels</button>

            <?php echo $this->helpButton(); ?>
        </form>
    </div>

    <div ng-switch="data.mode.name">
        <div ng-switch-when="Browse">
            <?php echo $this->helpBox('Select a country and filter set and view the corresponding data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_processing.html">detailed documentation</a>.'); ?>
        </div>
        <div ng-switch-when="Contribute JMP">
            <?php echo $this->helpBox('Select questionnaires and filters and edit existing or new data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input2.html#di-jmp">detailed documentation</a>.'); ?>
        </div>
        <div ng-switch-when="Contribute NSA">
            <?php echo $this->helpBox('Select a country and edit existing or new data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_input2.html#di-nsa">detailed documentation</a>.'); ?>
        </div>
    </div>
    <!-- Selection panel for filters and questionnaires -->
    <form name="selectionForm">
        <div class="row show-grid" ng-show="expandSelection">

            <!-- Filter selection -->
            <div class="col-md-6" ng-if="(data.questionnaires.length || data.mode.isContribute) && !data.mode.isSector">
                <div class="row" ng-class="{'has-error':!data.filters.length}">
                    <div class="col-md-12">
                        <h3 class="control-label">Filter (rows) <small ng-if="!data.filters.length">(Required)</small></h3>
                    </div>

                    <div class="col-md-12">
                        <tabset>
                            <tab heading="Filter set" >
                                <gims-select
                                    model="data.filterSet"
                                    api="filterSet"
                                    placeholder="Select filter set"
                                    disabled="isLoading"
                                    style="width: 100%">
                                </gims-select>
                            </tab>
                            <tab heading="Filter's children">
                                <gims-filter
                                        model="data.filter"
                                        name="filter"
                                        show-selection-path="true"
                                        disabled="isLoading">
                                </gims-filter>
                            </tab>
                            <tab heading="Filters ({{data.filters.length}})">
                                <gims-filter
                                        model="data.filters"
                                        name="filters"
                                        query-params="filterFields"
                                        show-selection-path="true"
                                        disabled="isLoading"
                                        multiple>
                                </gims-filter>
                            </tab>
                        </tabset>
                    </div>
                </div>
            </div>

            <!-- Questionnaires selection -->
            <div class="col-md-6">
                <div class="row" ng-class="{'has-error':!data.questionnaires.length && !data.mode.isContribute}">

                    <div>
                        <div class="col-md-12">
                            <h3 class="control-label" ng-if="!data.mode.isSector">Questionnaires (columns) <small ng-if="!data.questionnaires.length && !data.mode.isContribute">(Required)</small></h3>
                        </div>

                        <div class="col-md-12">
                            <tabset>
                                <tab heading="Country">
                                    <gims-select
                                            model="data.country"
                                            api="country"
                                            queryparams="countryParams"
                                            placeholder="Select a country"
                                            change-url="false"
                                            disabled="isLoading"
                                            style="width: 100%">
                                    </gims-select>
                                </tab>
                                <tab heading="Survey" ng-if="!data.mode.isSector">
                                    <gims-select
                                        model="data.survey"
                                        api="survey"
                                        queryparams="surveyParams"
                                        placeholder="Select survey"
                                        search-attributes="code,name"
                                        custom-selection-template="{{surveysTemplate}}"
                                        custom-result-template="{{surveysTemplate}}"
                                        change-url="false"
                                        disabled="isLoading"
                                        style="width: 100%">
                                    </gims-select>
                                </tab>
                                <tab heading="Questionnaires ({{data.questionnaires.length}})" ng-if="!data.mode.isSector">
                                    <gims-select
                                            model="data.questionnaires"
                                            name="questionnaires"
                                            api="questionnaire"
                                            queryparams="questionnaireParams"
                                            placeholder="Select questionnaires"
                                            disabled="isLoading"
                                            multiple
                                            style="width: 100%">
                                    </gims-select>
                                </tab>
                            </tabset>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <!-- Tabs parts -->
    <tabset class="nav-data-centered" ng-if="(data.mode.isSector && data.filter) || data.filters.length && (data.questionnaires.length || data.mode.isContribute)">
        <tab ng-repeat="part in data.parts" heading="{{part.name}}" select="data.part = part"></tab>
    </tabset>

</div>



<!-- Table of filters, questionnaires and answers. Display in full width when there are too much elements -->
<div disable-animate ng-if="(data.mode.isSector && data.filter) || data.filters.length && (data.questionnaires.length || data.mode.isContribute)" class="container gims-full-width-container">

    <div class="row">
        <div class="col-md-12">
            <form name="answersForm" novalidate>
                <table class="table table-bordered table-condensed table-filter" ng-class="{'is-computing': data.isComputing}">

                    <!-- Head part : including country, survey code and survey year -->
                    <tbody>

                        <!-- Action buttons (first row) -->
                        <tr>
                            <!-- Add a new empty questionnaire -->
                            <td style="width:350px">
                                <a class="btn btn-default btn-sm"
                                   ng-click="addQuestionnaire();"
                                   ng-if="data.mode.isContribute">
                                    <i class="fa fa-gims-add"></i> Add new questionnaire
                                </a>
                            </td>

                            <td ng-repeat="questionnaire in data.questionnaires track by $index" ng-class="{'showLabels': questionnaire.showLabels}">

                                <!-- Display errors on questionnaires / surveys integrity data structure (like two different years for the same survey or two countries for the same survey -->
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.duplicateCountryCode" tooltip="Surveys may not have the same country more than once" tooltip-placement="left"><i class="fa fa-warning"></i></a>
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.codeAndYearDifferent" tooltip="Surveys with the same code may have the same year" tooltip-placement="left"><i class="fa fa-warning"></i></a>
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.countryAlreadyUsedForExistingSurvey" tooltip="This country is already assigned to a survey with the same code" tooltip-placement="left"><i class="fa fa-warning"></i></a>
                                <a class="btn btn-warning btn-xs" ng-if="questionnaire.errors.surveyExistWithDifferentYear" tooltip="This survey already exists with different year : {{questionnaire.survey.existingYear}}" tooltip-placement="left"><i class="fa fa-warning"></i></a>

                                <!-- mark new questionnaire / is loading -->
                                <a class="btn btn-sm" ng-if="!questionnaire.id || questionnaire.isLoading" tooltip="New survey" tooltip-placement="left" ><i class="fa fa-lg" ng-class="{'fa-asterisk':!questionnaire.isLoading, 'fa-gims-loading':questionnaire.isLoading}"></i></a>
                                <span><gims-questionnaire-menu questionnaire="questionnaire"></gims-questionnaire-menu></span>
                            </td>
                        </tr>

                        <!-- Questionnaire's geoname row-->
                        <tr class="active" ng-if="data.questionnaires.length">
                            <td></td>
                            <td ng-if="data.selectedQuestionnaireForLabels" class="text-center">{{data.selectedQuestionnaireForLabels.geoname.country.name}} </td>
                            <td ng-repeat="questionnaire in data.questionnaires track by $index">
                                <div ng-switch="!!questionnaire.id">
                                    <div ng-switch-when="true" class="text-center">
                                        <div name="questionnaireForm" class="input-group input-group-sm">
                                            <div class="input-group-addon"><i class="fa fa-fw fa-gims-questionnaire"></i></div>
                                            <input ng-disabled="true" type="text" class="text-center" placeholder="Country" ng-model="questionnaire.geoname.country.name" name="country" />
                                        </div>
                                    </div>
                                    <div ng-switch-when="false" class="has-error">
                                        <ng-form name="questionnaireForm">
                                            <gims-select
                                                required
                                                disabled="data.mode.isSector || questionnaire.id || questionnaire.isLoading"
                                                api="country"
                                                model="questionnaire.geoname.country"
                                                queryparams="countryParams"
                                                placeholder="Country"
                                                change-url="false"
                                                style="width: 100%"
                                                ng-change="checkAndCompleteQuestionnaire(questionnaire)">
                                            </gims-select>
                                        </ng-form>
                                    </div>
                                </div>
                            </td>
                        </tr>

                        <!-- Survey's code row -->
                        <tr class="active" ng-if="data.questionnaires.length">
                            <td></td>
                            <td ng-if="data.selectedQuestionnaireForLabels" class="text-center">{{data.selectedQuestionnaireForLabels.survey.code}}</td>
                            <td ng-repeat="questionnaire in data.questionnaires track by $index" class="text-center">
                                <ng-form name="questionnaireForm" class="input-group input-group-sm" ng-class="{'has-error':questionnaireForm.code.$invalid}">
                                    <div class="input-group-addon"><i class="fa fa-fw fa-gims-survey"></i></div>
                                    <input ng-disabled="questionnaire.survey.id || questionnaire.isLoading" type="text" class="text-center" placeholder="Code" ng-model="questionnaire.survey.code" name="code" required ng-class="{'error':questionnaire.errors.duplicateCountryCode || questionnaire.errors.codeAndYearDifferent || questionnaireForm.code.$invalid}" ng-blur="checkAndCompleteQuestionnaire(questionnaire)"/>
                                </ng-form>
                            </td>
                        </tr>

                        <!-- Survey's year row -->
                        <tr class="active" ng-if="data.questionnaires.length">
                            <td>
                                <button class="btn btn-default btn-sm pull-right" ng-if="data.questionnaires.length > 1" ng-click="orderQuestionnaires(false)"><i class="fa fa-sort-amount-asc fa-rotate-270"></i> Sort by year</button>
                            </td>
                            <td ng-if="data.selectedQuestionnaireForLabels" class="text-center">{{data.selectedQuestionnaireForLabels.survey.year}}</td>
                            <td ng-repeat="questionnaire in data.questionnaires track by $index">
                                <ng-form name="questionnaireForm" class="input-group input-group-sm" ng-class="{'has-error':questionnaireForm.year.$invalid}">
                                    <div class="input-group-addon"><i class="fa fa-fw fa-gims-survey"></i></div>
                                    <input ng-disabled="questionnaire.survey.id || questionnaire.isLoading" type="number" class="text-center" placeholder="Year" ng-model="questionnaire.survey.year" name="year" min="1980" max="2015" size="4" required ng-class="{'error': questionnaire.errors.codeAndYearDifferent || questionnaireForm.year.$invalid}" ng-blur="checkAndCompleteQuestionnaire(questionnaire)"/>
                               </ng-form>
                           </td>
                        </tr>

                        <!-- Population row -->
                        <tr class="active" ng-if="data.questionnaires.length && data.mode.isSector">
                            <td>
                            </td>
                            <td ng-if="data.selectedQuestionnaireForLabels"></td>
                            <td class="text-center" ng-repeat="questionnaire in data.questionnaires track by $index">
                                <ng-form name="populationForm" class="input-group input-group-sm" ng-class="{'has-error':populationForm.value.$invalid}" tooltip="Leave empty to use official population data">
                                    <div class="input-group-addon"><i class="fa fa-fw" ng-class="{'fa-gims-population':!questionnaire.populations[data.part.id].isLoading,'fa-gims-loading':questionnaire.populations[data.part.id].isLoading}"></i></div>
                                    <input  type="number"
                                            class="text-center"
                                            placeholder="Population"
                                            min="0"
                                            name="value"
                                            ng-focus="setInitialValue(questionnaire.populations[data.part.id], questionnaire.populations[data.part.id].population)"
                                            ng-blur="savePopulation(questionnaire, questionnaire.populations[data.part.id])"
                                            ng-model="questionnaire.populations[data.part.id].population"
                                            ng-disabled="questionnaire.isLoading"
                                            />
                                </ng-form>
                            </td>
                        </tr>

                    </tbody>
                    <!-- End of table header-->

                    <!-- Label for questionnaire comments and close btn -->
                    <tbody ng-if="data.selectedQuestionnaireForComments">
                        <tr>
                            <td>
                                <a class="btn btn-default btn-xs" ng-click="data.selectedQuestionnaireForComments = null"><i class="fa fa-times"></i></a>
                                <i class="fa fa-comment"></i> Comments for {{data.selectedQuestionnaireForComments.geoname.country.name}}, {{data.selectedQuestionnaireForComments.survey.code}}, {{data.selectedQuestionnaireForComments.survey.year}}
                            </td>

                            <td ng-attr-colspan="{{!data.selectedQuestionnaireForLabels && data.questionnaires.length || data.selectedQuestionnaireForLabels && (data.questionnaires.length+1)}}" ng-if="data.selectedQuestionnaireForComments" class="text-center">

                                <ng-form name="labelForm" ng-if="data.mode.isContribute">
                                    <div class="input-group input-group-sm">
                                        <span class="input-group-addon"><i class="fa fa-comment"></i></span>
                                        <textarea class="form-control"
                                               ng-model="data.selectedQuestionnaireForComments.comments"
                                               ng-focus="data.selectedQuestionnaireForComments.initialComments = data.selectedQuestionnaireForComments.comments"
                                               ng-blur="saveComment(data.selectedQuestionnaireForComments)"
                                               name="label">
                                        </textarea>
                                    </div>
                                </ng-form>
                            </td>
                        </tr>
                    </tbody>

                    <tbody>
                        <!-- Filters and answers rows -->
                        <tr ng-repeat="filter in data.filters track by $index" ng-class="{'active':data.mode.isSector && filter.level < 2}">

                            <!-- Filter name column-->
                            <td class="filter">
                                <span class="btn btn-default btn-xs removeButton" style="vertical-align:top;" ng-click="removeFilter(filter)" tooltip="Hide this row and its children" tooltip-placement="right"><i class="fa fa-times"></i></span>

                                <span ng-if="isValidId(filter) || data.mode.isSector && filter.level != 1" ng-class="{'strong':filter.level == data.filters[0].level && !filter.sectorChild}" style="margin-left:{{(filter.level - data.filters[0].level) * 2}}em;">
                                    <i class="fa" style="color:{{filter.color}}" ng-class="{'fa-gims-filter':!filter.isLoading && isValidId(filter), 'fa-asterisk text-primary':!filter.isLoading && !isValidId(filter), 'fa-gims-loading':filter.isLoading}"></i>
                                    {{filter.name}}
                                    <a href="/admin/filter/edit/{{filter.id}}?returnUrl={{currentUrl}}"><i class="fa fa-pencil"></i></a>
                                </span>
                                <div ng-if="!isValidId(filter) && data.mode.isSector && filter.level == 1" style="display:inline-block;vertical-align:top;width:80%;margin-left:{{(filter.level - data.filters[0].level) * 2}}em;">
                                    <ng-form name="filterName" class="input-group" ng-class="{'has-error':filterName.$invalid}">
                                        <span class="input-group-addon"><i class="fa" ng-class="{'fa-asterisk':!filter.isLoading,'fa-gims-loading':filter.isLoading,'text-primary':!filterName.$invalid}"></i></span>
                                        <input type="text" name="name" ng-model="filter.name" placeholder="Facility name" required />
                                    </ng-form>
                                </div>
                            </td>

                            <!-- Questionnaires columns -->
                            <td ng-repeat="questionnaire in data.questionnaires track by $index">
                                <div class="row">
                                    <div class="col-md-8" ng-if="questionnaire.showLabels">
                                        <ng-form name="labelForm">
                                            <div class="input-group input-group-sm">
                                                <span class="input-group-addon"><i class="fa" ng-class="{'fa-question':!data.selectedQuestionnaireForLabels.survey.questions[filter.id].isLoading,'fa-gims-loading':data.selectedQuestionnaireForLabels.survey.questions[filter.id].isLoading}"></i></span>
                                                <input class="form-control"
                                                       ng-model="questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id]"
                                                       ng-blur="saveQuestion(questionnaire.survey.questions[filter.id], questionnaire)"
                                                       name="label"
                                                       ng-required="questionnaire.survey.questions[filter.id].answers[part.id][questionnaire.survey.questions[filter.id].value]"
                                                       ng-class="{'error': labelForm.label.$invalid}"/>
                                            </div>
                                        </ng-form>
                                    </div>
                                    <div ng-class="{'col-md-4': questionnaire.showLabels, 'col-md-12' : !questionnaire.showLabels}" gims-select-token questionnaire="questionnaire" filter="filter" part="data.part" question="questionnaire.survey.questions[filter.id]">
                                        <gims-cell questionnaire="questionnaire" filter="filter" part="data.part"></gims-cell>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        <tr ng-if="!data.mode.isSector">
                            <td  colspan="{{data.questionnaires.length + 1}}">
                                <a href ng-click="toggleShowQuestionnaireUsages()">
                                    <span ng-if="!data.showQuestionnaireUsages">Show Calculations / Estimations / Ratios</span>
                                    <span ng-if="data.showQuestionnaireUsages">Hide Calculations / Estimations / Ratios</span>
                                </a>
                            </td>
                        </tr>
                        <tr ng-if="data.showQuestionnaireUsages" ng-repeat="rule in data.questionnaireUsages[data.part.id] track by $index">

                            <!-- QuestionnaireUsage's rule name column-->
                            <td>
                                <i class="fa fa-gims-rule"></i> {{rule.name}}
                            </td>

                            <!-- QuestionnaireUsage's value name column -->
                            <td ng-repeat="questionnaire in data.questionnaires track by $index" style="text-align: center;" >
                                <span ng-if="rule.values[questionnaire.id]" gims-select-token part="data.part" questionnaire="questionnaire" rule="rule.values[questionnaire.id]">
                                    <!--@todo: actually don't work because we dont receive usage on request -->
                                    <a href gims-select-usage="rule.values[questionnaire.id].usage"><i class="fa fa-pencil" tooltip="Edit rule"></i></a><!--="/admin/rule/edit/{{rule.values[questionnaire.id].id}}"-->
                                    {{rule.values[questionnaire.id].value}}
                                </span>
                            </td>
                        </tr>

                        <tr ng-if="data.showQuestionnaireUsages && data.mode.isContribute">
                            <td>
                            </td>
                            <td ng-repeat="questionnaire in data.questionnaires track by $index" style="text-align: center;" >
                                <a class="btn btn-default btn-sm" href gims-add-usage questionnaire="questionnaire" part="data.part"><i class="fa fa-gims-add"></i> Add a rule</a>
                            </td>
                        </tr>

                        <tr ng-if="data.mode.isSector">
                            <td  colspan="{{data.questionnaires.length + 1}}">
                                <a class="btn btn-default btn-sm"
                                   ng-click="addEquipment();"
                                   ng-class="{'disabled': getFiltersByLevel(0).length != 1}">
                                    <i class="fa fa-gims-add"></i> Add new facility
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>

            </form>
        </div>
    </div>
</div>

<gims-rule-text-field-panel refresh="refresh(questionnairesPermissions, filtersComputing, questionnairesUsages)" readonly="!data.mode.isContribute"></gims-rule-text-field-panel>
