<div class="container">
    <form>
        <div class="row">
            <span class="col-md-6">
                <p><gims-select api="questionnaire" multiple model="questionnaire" placeholder="Select a questionnaire" style="width:100%;"></gims-select></p>
            </span>
        </div>
        <div class="row">
            <span class="col-md-6">
                <p><gims-select api="filterSet" model="filterSet" placeholder="Select a filter" style="width:100%;"></gims-select></p>
            </span>
            <span class="col-md-2">
                <p>&nbsp;<i class="fa fa-gims-loading" ng-show="isLoading"></i></p>
            </span>
        </div>
        <div class="row">
            <div class="col-md-6">
                <label class="checkbox">
                    <input type="checkbox" ng-model="showOnlyTopLevel" /> Show only top levels
                </label>
            </div>
        </div>
    </form>

    <div class="alert alert-info" ng-hide="table"><i class="fa fa-info-circle"></i> <?php echo $this->translate('Select parameters to show table here.') ?></div>
    <div ng-grid="gridOptions" class="gridStyle"></div>
</div>