<div class="container">

    <div class="navbar navbar-default hidden-print">
        <a class="navbar-brand" href="#">Questionnaires</a>
        <form class="navbar-form">
            <?php echo $this->helpButton(); ?>
        </form>
    </div>

    <?php echo $this->helpBox('View filtered data per survey for the selected countries and export the corresponding data. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/data_processing.html">detailed documentation</a>.'); ?>

    <form>
        <div class="row">
            <span class="col-md-6">
                <p><gims-select api="country" model="country" placeholder="<?php echo $this->translate('Select a country') ?>" format="name" style="width:100%;" multiple="multiple"/></p>
            </span>
        </div>
        <div class="row">
            <span class="col-md-6">
                <p><gims-select api="filterSet" model="filterSet" placeholder="<?php echo $this->translate('Select a filter set') ?>" style="width:100%;"/></p>
            </span>
            <span class="col-md-2">
                <p>&nbsp;<i class="fa fa-gims-loading" ng-show="isLoading"></i></p>
            </span>
        </div>
        <div class="row">
            <span class="form-group col-md-6">
                <a href="{{exportUrl}}" target="_blank" class="btn btn-default" ng-class="{disabled: !exportUrl}"><i class="fa fa-download"></i> Export</a>
            </span>
        </div>
    </form>

    <div class="alert alert-info" ng-hide="columnDefs"><i class="fa fa-info-circle"></i> <?php echo $this->translate('Select parameters to show table here.') ?></div>
    <div ng-grid="gridOptions" class="gridStyle" ng-show="columnDefs"></div>
</div>
