<div class="container">

    <h2>
        <ul class="breadcrumb">
            <span class="active pull-right"><i class="fa fa-fw fa-gims-questionnaire"></i></span>
            <li><a href="/admin/survey">Surveys</a></li>
            <li><a href="/admin/survey/edit/{{survey.id}}#2">{{survey.code}}</a></li>
            <li class="active">{{survey.code}} - {{questionnaire.geoname.name}}</li>
        </ul>
    </h2>
    <form name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('questionnaire'); ?>

        <tabset style="margin-top: 20px">
            <tab heading="General" active="tabs[0]" select="selectTab(0)">

                <div class="form-group" ng-class="{'has-error': myForm.status.$invalid}" ng-show="questionnaire.id">
                    <label class="control-label col-sm-2" for="questionnaire.status">Status</label>
                    <div class="col-sm-2">
                        <select class="form-control" id="questionnaire.status" name="state" ng-model="questionnaire.status"
                                ng-options="c.value as c.text for c in status" ng-disabled="statusDisabled"></select>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.geoname.$invalid}">
                    <label class="control-label col-sm-2" for="questionnaire.geoname">Country</label>
                    <div class="col-sm-6">
                        <gims-select api="geoname"
                                     model="questionnaire.geoname"
                                     name="geoname"
                                     placeholder="<?php echo $this->translate('Select a country') ?>"
                                     style="width: 100%"
                                     change-url="false"
                                     required>
                                 </gims-select>
                    </div>
                    <div class="col-sm-2">
                        <span ng-show="myForm.geoname.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.dateObservationStart.$invalid}">
                    <label class="control-label col-sm-2" for="questionnaire.dateObservationStart">Observation start</label>

                    <div class="col-sm-3 col-md-2">
                        <span class="input-group">
                            <input id="questionnaire.dateObservationStart" class="form-control" type="text" name="dateObservationStart"
                                   ng-model="questionnaire.dateObservationStart"
                                   is-open="dateObservationStartOpened"
                                   required
                                   datepicker-popup/>
                            <gims-datepicker-button class="input-group-btn"></gims-datepicker-button>
                        </span>
                    </div>
                    <div class="col-sm-2">
                        <span ng-show="myForm.dateObservationStart.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': myForm.dateObservationEnd.$invalid}">
                    <label class="control-label col-sm-2" for="questionnaire.dateObservationEnd">Observation end</label>

                    <div class="col-sm-3 col-md-2">
                        <span class="input-group">
                            <input id="questionnaire.dateObservationEnd" class="form-control" type="text" name="dateObservationEnd"
                                   ng-model="questionnaire.dateObservationEnd"
                                   is-open="dateObservationEndOpened"
                                   required
                                   datepicker-popup/>
                            <gims-datepicker-button class="input-group-btn"></gims-datepicker-button>
                        </span>
                    </div>
                    <div class="col-sm-2">
                        <span ng-show="myForm.dateObservationEnd.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label col-sm-2" for="questionnaire.comments">Comments</label>
                    <div class="col-sm-6">
                        <textarea class="form-control" id="questionnaire.comments" name="comments" ng-model="questionnaire.comments"></textarea>
                    </div>
                </div>

            </tab>

            <tab heading="Rule - Filter" ng-if="questionnaire.id" active="tabs[1]" select="selectTab(1)">
                <gims-relations relation="FilterQuestionnaireUsage" properties="['questionnaire', 'rule', 'filter', 'part']" justification="true"></gims-relations>
            </tab>

            <tab heading="Rule" ng-if="questionnaire.id" active="tabs[2]" select="selectTab(2)">
                <gims-relations relation="QuestionnaireUsage" properties="['questionnaire', 'rule', 'part']" justification="true"></gims-relations>
            </tab>

            <tab heading="Users" ng-if="questionnaire.id" active="tabs[3]" select="selectTab(3)">
                <gims-relations relation="UserQuestionnaire" properties="['questionnaire', 'user', 'role']"></gims-relations>
            </tab>
        </tabset>
    </form>

    <?php echo $this->metadata('questionnaire'); ?>
</div> <!-- /container -->