<div class="container">

    <h1>Sector data</h1>

    <div class='navbar navbar-default hidden-print'>
        <form class='navbar-form'>
            <div class='btn-group'>
                <button class='btn btn-default' ng-click='cancel();'><i class='fa fa-chevron-left'></i> Cancel</button>
                <button class='btn btn-primary' ng-click='save();' ng-disabled='answersForm.$invalid || selectionForm.$invalid || !filters || filters.length == 0 || !dates || dates.length == 0'><i class='fa fa-check'></i> Save</button>
            </div>
            <div class='btn-group'>
                <a href='/admin/filter' target='_blank' class='btn btn-default' ><i class='fa fa-gims-filter'></i> Manage filters</a>
                <a href='/admin/filter/new' target='_blank' class='btn btn-default' ><i class='fa fa-gims-filter'></i> Add filter</a>
            </div>
            <i class="pull-right fa fa-gims-loading fa-2x"  ng-show="isLoading" style='margin-top:5px'></i>
        </form>
    </div>

    <form name='selectionForm'>
        <div class="row show-grid">

            <div class='col-sm-6 col-md-5'>

                <div class='row show-grid'>
                    <div class='col-md-12'>
                        <label>Country</label>
                        <gims-select api="country" model="country" queryparams='countryQueryParams' disabled='true' placeholder="<?php echo $this->translate('Select a country') ?>" format="name" style="width:100%;"/>
                    </div>
                </div>
                <div class='row show-grid'>
                    <div class='col-md-12'>
                        <label>Part</label>
                        <p><gims-select api="part" model="part" disabled='true' placeholder="<?php echo $this->translate('Select a part') ?>" style="width:100%;"/></p>
                    </div>
                </div>
                <div class='row show-grid'>
                    <div class='col-md-12'>
                        <label for="fsName">Filter set name</label>
                        <input type="text" ng-model="filterSetName" class="form-control" id="fsName">
                    </div>
                </div>
            </div>

            <div class="col-sm-12 col-md-7">
                <div class='row'>
                    <div class='col-md-12'>
                        <label>Filter selection</label>
                    </div>
                </div>
                <div class='row show-grid'>
                    <div class='col-md-6'>
                        <div class="radio">
                            <label>
                                <input type="radio" name="selectionMode" id="selectByChildren1" ng-model='selectByChildren' value="true">
                                Select all children of selected filter
                            </label>
                        </div>
                    </div>
                    <div class='col-md-6'>
                        <div class="radio">
                            <label>
                                <input type="radio" name="selectionMode" id="selectByChildren2"  ng-model='selectByChildren' value="false">
                                Select filters one by one
                            </label>
                        </div>
                    </div>
                </div>

                <div class='row'>
                    <p class='col-md-12'>
                        <gims-select    ng-show='selectByChildren == "false"'
                                        name='filters'
                                        api="filter"
                                        queryparams="params"
                                        model="filters"
                                        placeholder="Select parent"
                                        container-css-class='select2list'
                                        current-context-element='?returnUrl=/admin/filter/edit/{{filter.id}}'
                                        custom-selection-template="{{select2Template}}"
                                        custom-result-template="{{select2Template}}"
                                        multiple
                                        style="width: 100%" >
                        </gims-select>

                        <gims-select    ng-show='selectByChildren == "true"'
                                        name='filter'
                                        api="filter"
                                        queryparams="params"
                                        model="filter"
                                        placeholder="Select parent"
                                        container-css-class='select2list'
                                        current-context-element='?returnUrl=/admin/filter/edit/{{filter.id}}'
                                        custom-selection-template="{{select2Template}}"
                                        custom-result-template="{{select2Template}}"
                                        style="width: 100%" >
                        </gims-select>
                    </p>
                </div>
            </div>
        </div>
    </form>

</div>




<div class='tableContainer' ng-class="{'gims-fullweight-container':dates.length >= 8, 'container':dates.length < 8}">
    <div class='row'>


        <form class='col-md-12' name='answersForm' novalidate>
            <table class='table table-bordered'>
                <thead>
                    <tr>
                        <th>
                            <button class='btn btn-success btn-sm' ng-click='addDate();'><i class='fa fa-plus'></i> Add date</button>
                        </th>
                        <th class='text-center' ng-repeat='date in dates track by $index'>
                            <button class='btn btn-danger btn-sm' ng-click='removeDate($index)'><i class='fa fa-trash-o'></i></button>
                        </th>
                    </tr>
                    <tr class='active'>
                        <td>Year</td>
                        <td ng-repeat='date in dates track by $index'>
                            <ng-form name='dateForm'>
                                <input type='number' ng-model='date.value' name='annee' min='1980' max='2015' size="4" required ng-class="{'error':dateForm.annee.$invalid}" ng-pattern='getUsedYearsPattern()'/>
                           </ng-form>
                           <!--ng-blur='validateUnicity($index)'-->
                       </td>
                    </tr>
                    <tr>
                       <td><!-- Population --></td>
                       <td class='text-center' ng-repeat='date in dates track by $index'></td>
                    </tr>
                </thead>

                <tbody ng-repeat="question in questions">
                    <tr class='active'>
                        <td colspan='{{dates.length+1}}' class='text-center'><strong>{{question.name}}</strong> ({{question.desc}})</td>
                    </tr>
                    <tr ng-repeat="filter in filters">
                        <td>{{filter.name}}</td>
                        <td ng-repeat='date in dates track by $index'>
                            <ng-form name='valueForm'>
                                <input type='number' ng-disabled='!date.value || !filter' min='0' ng-init='init(filter,question,$index)' ng-model='values[filter.id][question.name][$index]' required ng-class="{'error':valueForm.annee.$invalid}"/>
                            </ng-form>
                        </td>
                    </tr>
                </tbody>
            </table>
        </form>
    </div>
</div>


<div class="container" ng-init="firstCol='4.5em';lastCol='7em';">

</div>