<div>
    <ul class="gims-dropdown-menu pull-right" role="menu">
        <li class="dropdown-header">Information</li>
        <li ng-switch="getCellType(questionnaire, filter, part.id)">
            <a ng-switch-when="loading"><i class="fa fa-fw fa-gims-loading"></i></a>
            <a ng-switch-when="error"><i class="fa fa-fw fa-warning text-warning"></i> Answer entered is invalid</a>
            <a ng-switch-when="answer"><i class="fa fa-fw fa-question"></i> Manually answered</a>
            <a ng-switch-when="rule"><i class="fa fa-fw fa-gims-rule"></i> Computed with rules</a>
            <a ng-switch-when="summand"><i class="fa fa-fw fa-gims-summand"></i> Computed with summands</a>
            <a ng-switch-when="child"><i class="fa fa-fw fa-gims-child"></i> Computed with children</a>
            <a ng-switch-default> No value</a>
        </li>

        <li ng-if="questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id]">
            <a><i class="fa fa-question fa-fw"></i> {{questionnaire.survey.questions[filter.id].alternateNames[questionnaire.id]}} </a>
        </li>
        <li ng-if="isValidNumber(questionnaire.survey.questions[filter.id].answers[part.id][questionnaire.survey.questions[filter.id].value])" >
            <a><i class="fa fa-crosshairs fa-fw"></i> Given answer: {{questionnaire.survey.questions[filter.id].answers[part.id][questionnaire.survey.questions[filter.id].value]}}</a>
        </li>
        <li ng-if="isValidNumber(questionnaire.survey.questions[filter.id].answers[part.id][questionnaire.survey.questions[filter.id].value])">
            <a><i class="fa fa-crosshairs fa-fw"></i> Exact value : {{questionnaire.survey.questions[filter.id].answers[part.id][questionnaire.survey.questions[filter.id].value] * questionnaire.survey.questions[filter.id].answers[part.id].quality}}</a>
        </li>
        <li ng-if="questionnaire.survey.questions[filter.id].answers[part.id].error">
            <a><i class="fa fa-warning text-warning"></i> This answer has not been saved.</a>
        </li>

        <!-- Rules -->
        <li ng-if="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].second.length" class="divider"></li>
        <li ng-if="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].second.length" class="dropdown-header">Rules used in 2nd step of computation</li>
        <li ng-if="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].second.length">
            <ul ui-sortable="sortableOptions" ng-model="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].second">
                <li ng-repeat="usage in questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].second" data-questionnaire="{{questionnaire.id}}" data-part="{{part.id}}" data-filter="{{filter.id}}">
                    <a href gims-edit-usage="usage"><i class="fa fa-navicon fa-fw text-muted"></i><i class="fa fa-gims-rule fa-fw"></i> {{usage.rule.name}}</a>
                </li>
            </ul>
        </li>

        <li ng-if="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].first.length" class="divider"></li>
        <li ng-if="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].first.length" class="dropdown-header">Rules used in 1st step of computation</li>
        <li ng-if="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].first.length">
            <ul ui-sortable="sortableOptions" ng-model="questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].first">
                <li ng-repeat="usage in questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].first" data-questionnaire="{{questionnaire.id}}" data-part="{{part.id}}" data-filter="{{filter.id}}">
                    <a href gims-edit-usage="usage"><i class="fa fa-navicon fa-fw text-muted"></i><i class="fa fa-gims-rule fa-fw"></i> {{usage.rule.name}}</a>
                </li>
            </ul>
        </li>

        <!-- Summands -->
        <li ng-if="filter.summands.length" class="divider"></li>
        <li ng-if="filter.summands.length" class="dropdown-header">Summands used for computation</li>
        <li ng-repeat="summand in filter.summands">
            <a href="/admin/filter/edit/{{summand.id}}"><i class="fa fa-gims-filter fa-fw"></i> {{summand.name}}</a>
        </li>

        <li ng-if="questionnaire.survey.questions[filter.id].answers[part.id].id" class="divider"></li>
        <li ng-if="questionnaire.survey.questions[filter.id].answers[part.id].id" class="dropdown-header">Quality : {{questionnaire.survey.questions[filter.id].answers[part.id].quality * 100}} %</li>
        <li ng-if="questionnaire.survey.questions[filter.id].answers[part.id].id && questionnairesStatus[questionnaire.status] && questionnaire.survey.questions[filter.id].answers[part.id].permissions.update" style="padding:5px 30px">
            <div class="qualitySlider" ui-slider="qualitySlider.options" min="0" max="1" step="0.10" use-decimals ng-model="questionnaire.survey.questions[filter.id].answers[part.id].quality"></div>
        </li>
<!-- && questionnairesStatus[questionnaire.status]-->
        <!-- Actions -->
        <li class="divider"></li>
        <li class="dropdown-header">Actions</li>
        <li>
            <a href ng-click="openDiscussion({questionnaire: questionnaire.id, filter: filter.id})"><i class="fa fa-comments"></i> View discussion…</a>
        </li>

        <li ng-if="questionnairesStatus[questionnaire.status]">
            <a href ng-click="toggleExcludeRule(questionnaire, filter.id, part.id)"><i class="fa fa-gims-rule fa-fw"></i> {{excludeRuleExists(questionnaire.filterQuestionnaireUsagesByFilterAndPart[filter.id][part.id].second) ? 'Include in further computing' : 'Exclude from further computing'}}</a>
        </li>
        <li ng-if="data.mode.isContribute && questionnairesStatus[questionnaire.status]">
            <a href gims-add-usage questionnaire="questionnaire" filter="filter" part="part"><i class="fa fa-gims-rule fa-fw"></i> Add a rule…</a>
        </li>
        <li ng-if="data.mode.isContribute && questionnairesStatus[questionnaire.status]">
            <a href ng-if="questionnaire.survey.questions[filter.id].isAbsolute" ng-click="toggleQuestionAbsolute(questionnaire, questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[part.id])"><i class="fa fa-fw">%</i> Set question as percent value</a>
            <a href ng-if="!questionnaire.survey.questions[filter.id].isAbsolute" ng-click="toggleQuestionAbsolute(questionnaire, questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[part.id])"><i class="fa fa-fw fa-plus-square-o"></i> Set question as absolute value</a>
        </li>
        <li ng-if="data.mode.isContribute && questionnairesStatus[questionnaire.status] && questionnaire.survey.questions[filter.id].answers[part.id].id">
            <a href ng-click="deleteAnswer(questionnaire.survey.questions[filter.id], questionnaire.survey.questions[filter.id].answers[part.id])">
                <span class="text-danger"><i class="fa fa-trash-o fa-fw"></i> Delete answer</span>
            </a>
        </li>
    </ul>
</div>