<div>
    <ul class="gims-dropdown-menu pull-right" role="menu">


        <li class="dropdown-header">Information</li>
        <li><a><i class="fa fa-fw fa-flag"></i> Status: {{questionnaire.status|capital}}</a></li>
        <li ng-if="questionnaire.permissions.publish">
            <a href ng-click="toggleQuestionnaireCompletedPublished(questionnaire)" ng-if="questionnaire.status == 'published'">
                <i class="fa fa-fw fa-flag-o"></i> Unpublish
            </a>
            <a href ng-click="toggleQuestionnaireCompletedPublished(questionnaire)" ng-if="questionnaire.status == 'completed'">
                <i class="fa fa-fw fa-flag-checkered"></i> Publish
            </a>
        </li>

        <li class="divider"></li>

        <!-- Save a single questionnaire -->
        <li>
            <a ng-click="saveAll(questionnaire)"
               ng-if="data.mode.isContribute && !questionnaire.id"
               ng-class="{'disabled' : !questionnaireCanBeSaved(questionnaire)}" href>
                <span class="text-primary"><i class="fa fa-fw fa-save"></i> Save this survey</span>
            </a>
        </li>

        <li ng-if="data.mode.isContribute && questionnaire.id" class="dropdown-header">
            Actions
        </li>
        <li><a href ng-click="openDiscussion({questionnaire: questionnaire.id})"><i class="fa fa-comments"></i> View discussion</a></li>
        <li><a href ng-click="removeQuestionnaire(questionnaire)"><i class="fa fa-times fa-fw"></i> Hide this column</a></li>


        <!-- Questions labels edition button, display an additionnal column -->
        <li ng-if="data.mode.isContribute">
            <a ng-click="toggleShowLabels(questionnaire)" href>
                <i class="fa fa-question fa-fw"></i>
                <span ng-if="questionnaire.showLabels">Hide</span>
                <span ng-if="!questionnaire.showLabels">Show</span>
                question labels
            </a>
        </li>

        <!-- Edit questionnaire comment, display an additionnal column -->
        <li ng-if="data.mode.isContribute">
            <a ng-click="data.showQuestionnaireComments = !data.showQuestionnaireComments;" href>
                <i class="fa fa-comment fa-fw"></i>
                <span ng-if="data.showQuestionnaireComments">Hide</span>
                <span ng-if="!data.showQuestionnaireComments">Show</span>
                questionnaire comments
            </a>
        </li>

        <!-- Add questionnaireUsage -->
        <li ng-if="data.mode.isContribute">
            <a href gims-add-usage questionnaire="questionnaire" part="data.part"><i class="fa fa-gims-rule fa-fw"></i> Add a rule</a>
        </li>

        <li ng-if="data.mode.isContribute && questionnaire.id" class="divider"></li>

        <!-- Links to admin -->
        <li ng-if="data.mode.isContribute && questionnaire.id" class="dropdown-header">
            Links to admin section
        </li>

        <li  ng-if="data.mode.isContribute && questionnaire.survey.id">
            <a href="/admin/survey/edit/{{questionnaire.survey.id}}?returnUrl={{currentUrl}}">
                <i class="fa fa-gims-survey fa-fw"></i>
                Edit Survey
            </a>
        </li>

        <!-- Link to questionnaire in /admin/ section -->
        <li ng-if="data.mode.isContribute && questionnaire.id">
            <a  href="/admin/questionnaire/edit/{{questionnaire.id}}?returnUrl={{currentUrl}}">
                <i class="fa fa-gims-questionnaire fa-fw"></i>
                Edit Questionnnaire
            </a>
        </li>

    </ul>
</div>