<div class="col-md-1">
    <span class="fa-stack fa-lg" ng-class="{'text-primary': activity.action == 'update', 'text-success':activity.action == 'create', 'text-danger': activity.action == 'delete'}">
        <i class="fa fa-question fa-stack-2x "></i>
    </span>
</div>

<div class="col-md-11">
    <h3 style="margin-top:5px;" ng-class="{'text-primary': activity.action == 'update', 'text-success':activity.action == 'create', 'text-danger': activity.action == 'delete'}">
        <span ng-switch="activity.action">
            <span ng-switch-when="update">Answer updated</span>
            <span ng-switch-when="create">Answer created</span>
            <span ng-switch-when="delete">Answer deleted</span>
        </span>
        <a href="" class="btn btn-default btn-xs" ng-click="activity.showDetails = !activity.showDetails"><i class="fa fa-eye"></i> View details</a>
        <a href="/contribute/jmp?filters={{activity.data.filter.id}}&questionnaires={{activity.data.questionnaire.id}}" class="btn btn-default btn-xs"><i class="fa fa-gims-questionnaire"></i> View in table</a>
    </h3>

    <gims-activity-changes></gims-activity-changes>
    <gims-activity-data ng-show="activity.showDetails"></gims-activity-data>
</div>
