<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-gims-rule"></i></span>
            <li><a href="/admin/rule">Rules</a></li>
            <li class="active">{{rule.name}}</li>
        </ul>
    </h2>
    <?php echo $this->helpBox('Edit the rule\'s label and formula. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/rule.html">detailed documentation</a>.'); ?>

    <form name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('rule'); ?>

        <tabset style="margin-top: 20px">
            <tab heading="General">

                <div class="form-group" ng-class="{'has-error': myForm.name.$invalid}">
                    <label class="control-label col-sm-1" for="rule.name"><?php echo $this->translate("Name"); ?></label>
                    <div class="col-sm-6">
                        <input id="rule.name" type="text" name="name" ng-model="rule.name" required ng-minlength="3"/>
                    </div>
                    <div class="col-sm-3">
                        <span ng-show="myForm.name.$error.required" class="help-block"><?php echo $this->translate("Required"); ?></span>
                        <span ng-show="myForm.name.$error.minlength" class="help-block"><?php echo sprintf($this->translate("It must be at least %u characters long"), 3); ?></span>
                    </div>
                </div>

                <div class="form-group" ng-class="{'has-error': messages.length}">
                    <label class="control-label col-sm-1" for="rule.formula"><?php echo $this->translate("Formula"); ?></label>
                    <div class="col-sm-11">
                        <div class="input-group">
                            <div id="rule.formula" class="form-control" ui-ace="aceOptions" name="formula" ng-model="rule.formula" style="height:100px"></div>
                            <span gims-rule-wizard class="input-group-addon input-group-addon-clickable"><i class='fa fa-gims-wizard'></i></span>
                        </div>
                    </div>
                    <div class="form-group" ng-class="{'has-error': messages}">
                        <span class="control-label col-sm-1" ></span>
                        <div class="col-sm-11">
                            <ul class="help-block">
                                <li ng-repeat="message in messages" class="">{{message}}</li>
                            </ul>

                            <div ng-if="!messages.length">
                                <gims-formula structure="rule.structure"></gims-formula>
                            </div>
                        </div>
                    </div>
                </div>

            </tab>

            <tab heading="Filter - Questionnaire" ng-if="rule.id">
                <gims-relations relation="FilterQuestionnaireUsage" properties="['rule', 'filter', 'questionnaire', 'part']" justification="true"></gims-relations>
            </tab>

            <tab heading="Questionnaire" ng-if="rule.id">
                <gims-relations relation="QuestionnaireUsage" properties="['rule', 'questionnaire', 'part']" justification="true"></gims-relations>
            </tab>

            <tab heading="Filter - Country" ng-if="rule.id">
                <gims-relations relation="FilterGeonameUsage" properties="['rule', 'filter', 'geoname', 'part']" justification="true"></gims-relations>
            </tab>
        </tabset>
    </form>
    <?php echo $this->metadata('rule'); ?>
</div> <!-- /container -->
