<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album', array('action'=>'add'));?>">Add new album</a>
</p>
<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<tr ng-repeat="album in albums">
    <td>{{album.title}}</td>
    <td>{{album.artist}}</td>
    <td>
        <a href="#/album/{{album.id}}">Edit</a>
        <a href="<?php //echo $this->url('album', array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
    </td>
</tr>
</table>
