<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GIMS '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet('/css/application.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile('/js/min/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                    ->prependFile(array('/js/min/application.js',
                                        array(
                                            
                                            // CAUTION: This must be the exact same files in reverse order than in scripts/build.sh
//                                            '/js/min/common.js',
                                            '/js/min/bootstrap-alert.js',
                                            '/js/min/bootstrap-button.js',
                                            '/js/min/bootstrap-carousel.js',
                                            '/js/min/bootstrap-collapse.js',
                                            '/js/min/bootstrap-dropdown.js',
                                            '/js/min/bootstrap-modal.js',
                                            '/js/min/bootstrap-popover.js',
                                            '/js/min/bootstrap-scrollspy.js',
                                            '/js/min/bootstrap-tab.js',
                                            '/js/min/bootstrap-tooltip.js',
                                            '/js/min/bootstrap-transition.js',
                                            '/js/min/bootstrap-typeahead.js',
                                            '/js/min/jquery.js',
                                        )
                                    )) ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2005 - 2012 by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
