<?php

namespace Export\View\Helper;

/**
 * Send the excel document to the client as attached file
 *
 */
class ExcelSend extends \Zend\View\Helper\AbstractHelper
{

    /**
     * Send the excel document to the client as attached file
     * @param $workbook the workbook to send
     * @param $filename the filename suggested to save as for the end-user
     * @return null
     */
    public function __invoke(\PHPExcel $workbook, $filename = 'output.xlsx')
    {
        // Set properties
        $workbook->getProperties()->setCreator('GIMS');
        $workbook->getProperties()->setLastModifiedBy('GIMS');
        $workbook->getProperties()->setTitle($filename);
        $workbook->getProperties()->setSubject($filename);
        $workbook->getProperties()->setDescription('Generated by GIMS');

        // Save Excel 2007 file
        header("Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        header("Content-Disposition: attachment; filename=\"$filename\"");
        header("Expires: 0");
        header("Cache-Control: must-revalidate, post-check=0,pre-check=0");
        header("Pragma: public");
        $objWriter = new \PHPExcel_Writer_Excel2007($workbook);
        $objWriter->save('php://output');
    }

}

