<div class="modal-header">
    <button type="button" class="close" ng-click="$dismiss()"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title">Select existing rule</h4>
</div>

<div class="modal-body">
    <accordion>
        <accordion-group heading="Any rule by name" is-open="opened">
            <gims-select api="rule"
                         model="selection.rule"
                         queryParams="ruleFields"
                         change-url="false"
                         style="width: 100%">
            </gims-select>
        </accordion-group>
        <accordion-group heading="Suggested rules by same {{type}}" ng-repeat="type in types" ng-if="suggestedUsages[type].length">
            <ul class="list-unstyled">
                <li ng-repeat="usage in suggestedUsages[type]" ng-click="setRule(usage.rule)">
                    <a href><i class="fa fa-gims-rule"></i> {{usage.rule.name}}</a>
                </li>
            </ul>
        </accordion-group>
    </accordion>


</div>
<div class="modal-footer" ng-if="selection.rule" style="text-align:left">
    <strong>Selected rule : </strong> {{selection.rule.name}}
    <gims-formula structure="selection.rule.structure" ></gims-formula>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" ng-click="$dismiss()">Close</button>
    <button class="btn btn-primary pull-right" ng-click="selectRule(selection.rule)" ng-disabled="!selection.rule">Select</button>
</div>



