<div class="input-group">
    <div id="rule.formula" class="form-control" ui-ace="aceOptions" name="formula" ng-model="rule.formula"></div>
    <span class="input-group-addon input-group-addon-clickable" gims-rule-wizard>
        <i class="fa fa-gims-wizard fa-fw"></i>
    </span>
</div>

<div ng-show="messages.length" class="help-block alert alert-danger">
    <ul>
        <li ng-repeat="message in messages" class="text-danger">{{message}}</li>
    </ul>
</div>

<p ng-if="!messages.length && rule.structure.length" class='help-block alert alert-success'>
    <gims-formula structure="rule.structure"></gims-formula>
</p>
