<div class="modal-header">
    <button type="button" class="close" ng-click="$dismiss()"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <h4 class="modal-title">Syntax wizard</h4>
</div>

<div class="modal-body">

    <div class='form-horizontal'>
        <div class="form-group" ng-class="{'has-error': myForm.token.$invalid}">
            <label class="control-label col-md-2" for="token.selected"><?php echo $this->translate("Syntax"); ?></label>
            <div class="col-md-8">
                <p>
                    <select name="token" class="form-control"
                            id="token.selected"
                            ng-model="token.selected"
                            ng-options="t.name group by t.group for t in availableTokens"
                            style="width: 100%"
                            >
                        <option style="display:none" value="">Select a syntax to insert</option>
                    </select>
                </p>
            </div>
            <div class="col-md-offset-2 col-md-8">
                <p class="help-block" ng-show="token.selected.description">{{token.selected.description}}</p>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.rule" ng-class="{'has-error': myForm.rule.$invalid}">
            <label class="control-label col-md-2" for="token.rule"><?php echo $this->translate("Rule"); ?></label>
            <div class="col-md-8">
                <gims-select name="rule"
                             id="token.rule"
                             api="rule"
                             model="token.rule"
                             change-url="false"
                             placeholder="Select a rule"
                             style="width: 100%">
                </gims-select>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.filter" ng-class="{'has-error': myForm.filter.$invalid}">
            <label class="control-label col-md-2" for="token.filter"><?php echo $this->translate("Filter"); ?></label>
            <div class="col-md-8">
                <div class="radio">
                    <label>
                        <input type="radio" ng-model="token.filter" ng-value="currentValue" name='wizard-radio' />
                        {{currentValue.name}}
                    </label>
                </div>
                <div class="radio">
                    <label style="width: 100%">
                        <input type="radio" ng-checked="currentValue != token.filter" name='wizard-radio' />
                        <gims-select name="filter"
                                     id="token.filter"
                                     api="filter"
                                     model="token.filter"
                                     change-url="false"
                                     placeholder="Select a filter"
                                     style="width: 100%"
                                >
                        </gims-select>
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.questionnaire" ng-class="{'has-error': myForm.questionnaire.$invalid}">
            <label class="control-label col-md-2" for="token.questionnaire"><?php echo $this->translate("Questionnaire"); ?></label>
            <div class="col-md-8">
                <div class="radio">
                    <label>
                        <input type="radio" ng-model="token.questionnaire" ng-value="currentValue" name='wizard-questionnaire' />
                        {{currentValue.name}}
                    </label>
                </div>
                <div class="radio">
                    <label style="width: 100%">
                        <input type="radio" ng-checked="currentValue != token.questionnaire" name='wizard-questionnaire' />
                        <gims-select name="questionnaire"
                                     id="token.questionnaire"
                                     api="questionnaire"
                                     model="token.questionnaire"
                                     change-url="false"
                                     placeholder="Select a questionnaire"
                                     style="width: 100%"
                                >
                        </gims-select>
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.part" ng-class="{'has-error': myForm.part.$invalid}">
            <label class="control-label col-md-2" for="token.part"><?php echo $this->translate("Part"); ?></label>
            <div class="col-md-8">
                <div class="radio">
                    <label>
                        <input type="radio" ng-model="token.part" ng-value="currentValue" name='wizard-part' />
                        {{currentValue.name}}
                    </label>
                </div>
                <div class="radio">
                    <label style="width: 100%">
                        <input type="radio" ng-checked="currentValue != token.part" name='wizard-part' />
                        <gims-select name="part"
                                     id="token.part"
                                     api="part"
                                     model="token.part"
                                     change-url="false"
                                     placeholder="Select a part"
                                     style="width: 100%"
                                >
                        </gims-select>
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.year" ng-class="{'has-error': myForm.year.$invalid}">
            <label class="control-label col-md-2" for="token.year"><?php echo $this->translate("Year offset"); ?></label>
            <div class="col-md-8">
                <input type="number" name="year"
                       id="token.year"
                       min="-50"
                       max="50"
                       step="1"
                       ng-model="token.year"
                       placeholder="Select a year"
                       required
                        />
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.questionnaireUsage" ng-class="{'has-error': myForm.questionnaire.$invalid}">
            <label class="control-label col-md-2" for="token.questionnaire"><?php echo $this->translate("Questionnaire"); ?></label>
            <div class="col-md-8">
                <div class="radio" ng-repeat="suggestedQuestionnaire in suggestedQuestionnaires">
                    <label>
                        <input type="radio" ng-model="token.questionnaire" ng-value="suggestedQuestionnaire" name='wizard-questionnaire' />
                        {{suggestedQuestionnaire.name}}
                    </label>
                </div>
                <div class="radio">
                    <label style="width: 100%">
                        <input type="radio" ng-checked="currentValue != token.questionnaire" name='wizard-questionnaire' />
                        <gims-select name="questionnaire"
                                     id="token.questionnaire"
                                     api="questionnaire"
                                     model="token.questionnaire"
                                     change-url="false"
                                     placeholder="Select a questionnaire"
                                     style="width: 100%"
                                >
                        </gims-select>
                    </label>
                </div>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.questionnaireUsage" ng-class="{'has-error': myForm.questionnaire.$invalid}">
            <label class="control-label col-md-2" for="token.usage"><?php echo $this->translate("Usage"); ?></label>
            <div class="col-md-8">
                <p>
                    <select name="token" class="form-control"
                            id="token.usage"
                            ng-model="token.usage"
                            ng-options="u.part.name group by u.rule.name for u in suggestedQuestionnaireUsages"
                            style="width: 100%"
                            ng-disabled="!suggestedQuestionnaireUsages.length"
                            >
                        <option style="display:none" value="">Select a specific usage of rule</option>
                    </select>
                </p>
            </div>
        </div>
    </div>
    <div class='form-horizontal'>
        <div class="form-group" ng-show="token.selected.step" ng-class="{'has-error': myForm.step.$invalid}">
            <label class="control-label col-md-2" for="token.step"><?php echo $this->translate("Step 2"); ?></label>
            <div class="col-md-8">
                <input class="pull-left" type="checkbox" name="step" id="token.step" ng-model="token.step" style="margin-top:10px;"/>
                <p class="help-block" style="margin-left:20px;">In most cases the filter value referenced should be the one from the first step of computation, so the checkbox should be left unchecked. <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/rule.html#step"><i class="fa fa-gims-help" tooltip="Read more"></i></a></p>
            </div>
        </div>
    </div>

    <div class="row">
        <p class="col-md-12 help-block" ng-show="token.selected.filter || token.selected.questionnaire || token.selected.part">
            <i>Current</i> refers to the context where the rule is applied. It should be favored as much as possible. <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/rule.html#current"><i class="fa fa-gims-help" tooltip="Read more"></i></a></p>
        </p>
    </div>

</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" ng-click="$dismiss()">Close</button>
    <button class="btn btn-primary pull-right" ng-click="insertToken()" ng-disabled="!tokenCanBeInserted()">Insert at cursor position</button>
</div>



