<?php

namespace Application\View\Helper;

use Zend\ServiceManager\ServiceLocatorAwareInterface;

class Version extends \Zend\View\Helper\AbstractHtmlElement implements ServiceLocatorAwareInterface
{

    use \Zend\ServiceManager\ServiceLocatorAwareTrait;

    /**
     * Returns GIMS version based on configuration file generated by bin/build.sh
     * @return string
     */
    public function __invoke()
    {
        $config = $this->getServiceLocator()->getServiceLocator()->get('Config');

        if (isset($config['version'])) {
            return $config['version'];
        } else {
            return '';
        }
    }
}
