<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-gims-filter"></i></span>
            <li><a href="/admin/filter">Filters</a></li>
            <li class="active">{{filter.name}}</li>
        </ul>
    </h2>

    <?php echo $this->helpBox('Edit the filter\'s label and color as well as its parent/child filter(s). For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/filter.html">detailed documentation</a>.'); ?>

    <form novalidate name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('filter'); ?>

        <tabset style="margin-top: 20px" active="panes[0].active">
            <tab heading="General">

                <h2>Hierarchy <small> for {{filter.name}}</small></h2>

                <div class="form-group" ng-hide="isChapter">
                    <h3><small><label class="control-label col-md-2" for="parents">Parents</label></small></h3>
                    <div class="col-md-8">
                        <gims-filter model='filter.parents'
                                     name="parents"
                                     show-selection-path="true"
                                     show-edit-button="true"
                                     multiple>
                        </gims-filter>
                    </div>
                </div>

                <hr/>
                <br/>

                <div class="form-group"  ng-class="{'has-error': myForm.name.$invalid}">
                    <h4 class="control-label col-md-2" for="filter.name" style="background:{{filter.bgColor}};margin-top:0px;padding-bottom:7px;"><i class='fa fa-gims-filter' style='color:{{filter.color}}'></i> Filter Label</h4>
                    <div class="col-md-8">
                        <input type="text" name="name" ng-model="filter.name" required/>
                    </div>
                    <div class="col-md-2">
                        <span ng-show="myForm.name.$error.required" class="help-block">Required</span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2"></div>
                    <div class="col-md-10">
                        <div class="row">
                            <div class="col-md-2">
                                <div class='btn btn-default' colorpicker colorpicker-with-input="true" ng-model="filter.color" style='background-color:{{filter.color}}'><i class='fa fa-magic'></i></div> Color
                            </div>
                            <div class="col-md-3">
                                <div class='btn btn-default' colorpicker colorpicker-with-input="true" ng-model="filter.bgColor" style='background-color:{{filter.bgColor}}'><i class='fa fa-magic'></i></div> Background color

                            </div>
                        </div>
                    </div>
                </div>

                <hr/>

                <div class="form-group" ng-hide="isChapter">
                    <h3><small><label class="control-label col-md-2" for="children">Children</label></small></h3>
                    <div class="col-md-8">
                        <gims-filter model="filter.children"
                                     name="children"
                                     show-selection-path="true"
                                     show-edit-button="true"
                                     multiple>
                        </gims-filter>
                    </div>
                </div>

            </tab>

            <tab heading="Summands and organisation">

                <h2>Calculation</h2>
                <div class="form-group" ng-hide="isChapter">
                    <h3><small><label class="control-label col-md-2" for="summands">Summands</label></small></h3>
                    <div class="col-md-8">
                        <gims-filter model="filter.summands"
                                     name="summands"
                                     show-selection-path="true"
                                     show-edit-button="true"
                                     multiple>
                        </gims-filter>
                    </div>
                </div>

                <hr/>

                <h2>Organisation</small></h2>
                <div class="form-group" ng-hide="isChapter">
                    <h3><small><label class="control-label col-md-2" for="parents">Filter sets</label></small></h3>
                    <div class="col-md-8">
                        <gims-select    name='parents'
                                        api="filterSet"
                                        model="filter.filterSets"
                                        placeholder="Select parent"
                                        multiple
                                        style="width: 100%">
                        </gims-select>
                    </div>
                </div>
                
            </tab>

            <tab heading="Rule - Questionnaire" ng-if="filter.id">
                <gims-relations relation="FilterQuestionnaireUsage" properties="['filter', 'rule', 'questionnaire', 'part']" justification="true"></gims-relations>
            </tab>

            <tab heading="Rule - Country" ng-if="filter.id">
                <gims-relations relation="FilterGeonameUsage" properties="['filter', 'rule', 'geoname', 'part']" justification="true"></gims-relations>
            </tab>

        </tabset>

    </form>
</div>