<div class="container">

    <h2>
        <ul class="breadcrumb">
            <i class="active fa fa-gims-filter pull-right"></i>
            <li class="active"><a href="/admin/filter">Filter</a></li>
        </ul>
    </h2>

    <div class="row">
        <div class="col-md-9">
            <gims-filter model="selectedFilter" show-edit-button="true"> </gims-filter>
        </div>
        <div class="col-md-3 show-grid text-right" >
            <gims-link-new target="filter"></gims-link-new>
        </div>
    </div>

    <gims-grid api="filter" options="gridOptions" queryparams="queryparams"></gims-grid>

</div> <!-- /container -->
