<div class="container">

    <!-- Toolbar -->
    <div class="navbar navbar-default hidden-print">
        <a class="navbar-brand" href="#">Request roles</a>

        <form class="navbar-form">
            <?php echo $this->helpButton(); ?>
        </form>
    </div>

    <?php echo $this->helpBox('On this page, you can ask for the permissions you need. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/basics.html#ask-for-permissions">detailed documentation</a>.'); ?>


    <form name="myForm" class="form-horizontal">

        <div class="form-group" ng-class="{'has-error':!geonames.length}">
            <label class="control-label col-sm-3">Select countries</label>
            <div class="col-sm-7">
                <gims-select
                    model="geonames"
                    name="geonames"
                    api="geoname"
                    placeholder="Select geonames"
                    multiple
                    style="width: 100%">
                </gims-select>
            </div>
            <div class="col-sm-2">
                <span ng-if="!geonames.length" class="help-block">Required</span>
            </div>
        </div>

        <div class="form-group" ng-class="{'has-error':!roles.length}">
            <label class="control-label col-sm-3">Select roles</label>
            <div class="col-sm-7">
                <gims-select
                    model="roles"
                    name="roles"
                    api="role"
                    placeholder="Select roles"
                    multiple
                    required
                    style="width: 100%">
                </gims-select>

            </div>
            <div class="col-sm-2">
                <span ng-if="!roles.length" class="help-block">Required</span>
            </div>
        </div>

        <div class="form-group" ng-class="{'has-error':!types.selected.length}">
            <label class="control-label col-sm-3">Select survey type</label>
            <div class="col-sm-7">
                <ui-select multiple ng-model="types.selected" style="width: 100%;">
                    <ui-select-match placeholder="Select survey types">{{$item.display}}</ui-select-match>
                    <ui-select-choices repeat="type.value as type in surveyTypesList">
                        <div ng-bind-html="type.display | highlight: $select.search"></div>
                    </ui-select-choices>
                </ui-select>
            </div>
            <div class="col-sm-2">
                <span ng-if="!types.length" class="help-block">Required</span>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-3">&nbsp;</label>
            <div class="col-sm-7">
                <button class="btn btn-success" ng-click="sendRequest()" ng-disabled="myForm.$invalid || sending">Send roles request</button>
            </div>
        </div>
    </form>
    <div>
        <alert class="ng-trans ng-trans-fade-up" ng-repeat="alert in alerts" type="{{alert.type}}" close="closeAlert($index)">{{alert.msg}}</alert>

    </div>
</div>
