<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li><a href="/admin/survey">Surveys</a></li>
            <li><a id="survey-question-link" href="#">{{question.survey.code}}</a></li>
            <li class="active">{{question.name}}</li>
        </ul>
    </h2>


    <form novalidate name="myForm">

        <?php echo $this->crudButtons('question'); ?>

        <!--pre>{{question|json}}</pre-->

        <br/><br/>

        <div class="control-group form-horizontal row-fluid">
            <label class='control-label' for="question.type">Type</label>
            <div class='controls'>
                <select class='span5'
                        id="question.type"
                        name="type"
                        ng-model="question.type"
                        ng-change="initChoices()"
                        ng-options="c.value as c.text for c in types">
                </select>
            </div>
        </div>
        <div class="control-group form-horizontal row-fluid" ng-show='isChoices' ng-class="{error: myForm.filter.$invalid}">
            <label class='control-label' for="question.multiple">Number of choices wanted</label>
            <div class='controls'>
                <select class='span5'
                        name="question.multiple"
                        ng-model="question.multiple"
                        ng-options="p.value as p.text for p in multiple">
                </select>
            </div>
        </div>

        <div class="control-group form-horizontal row-fluid" ng-class="{error: myForm.filter.$invalid}">
            <label class='control-label' for="question.chapter">Parent question</label>
            <div class='controls'>
                <select class='span5'
                        name="question.chapter"
                        ng-model="question.chapter.id"
                        ng-options="p.id as p.name for p in chapterList">
                </select>
            </div>
        </div>

        <div class="control-group form-horizontal row-fluid" ng-show='isChapter' ng-class="{error: myForm.filter.$invalid}">
            <label class='control-label' for="question.final">Display mode</label>
            <div class='controls'>
                <label class='radio'><input type='radio' name='question.final' value='0' ng-model='question.final' checked>Behaviors like a folder and subquestions are displayed on their own page</label>
                <label class='radio'><input type='radio' name='question.final' value='1' ng-model='question.final'>Display all subquestions in one single page</label>
            </div>
        </div>




        <div class="control-group form-horizontal row-fluid" ng-hide='isChapter' ng-class="{error: myForm.filter.$invalid}">
            <label class='control-label' for="question.filter">Thematic</label>
            <div class='controls'>
                <gims-select    class='span5'
                                api="filter"
                                model="question.filter"
                                placeholder="Select a thematic">
                </gims-select>
                <span ng-show="myForm.filter.$error.required" class="help-inline">Required</span>
            </div>
        </div>



		<div class="control-group form-horizontal row-fluid" ng-hide='isChapter' ng-class="{error: myForm.name.$invalid}">
		    <label class='control-label' for="question.part">Zone</label>
            <div class='controls'>
                <gims-select    class="span5 input-medium"
                                id="question.parts"
                                name="type"
                                model="question.parts"
                                api="part"
                                multiple="multiple">
                </gims-select>
            </div>
		</div>



        <br/><br/>
		<div class="control-group form-horizontal"  ng-class="{error: myForm.name.$invalid}">
            <label class='control-label' for="question.name">Label</label>
            <div class='controls control-row'>
                <input class='span8' id="question.name" type="text" name="name" ng-model="question.name"/>
                <span ng-show="myForm.name.$error.required" class="help-inline">Required</span>
            </div>
        </div>
        <div class="control-group form-horizontal row-fluid"  ng-hide='isChapter' ng-class="{error: myForm.filter.$invalid}">
            <label class='control-label' for="question.compulsory">Compulsory</label>
            <div class='controls'>
                <select class='span2'
                        name="question.compulsory"
                        ng-model="question.compulsory"
                        ng-options="p.value as p.text for p in compulsory">
                </select>
            </div>
        </div>





        <br/><br/>
        <div ng-repeat="choice in question.choices" ng-show="isChoices" ng-class="{error: myForm.name.$invalid}">

            <div class="control-group form-horizontal">
                <label class='control-label' for="choice.label">Option {{$index+1}}</label>
                <div class='controls'>
                    <input id="choice.value" type="text" name="name" ng-model="choice.label" required class='span8'/>
                    <span ng-show="myForm.name.$error.required" class="help-inline">Required</span>
                </div>
            </div>

            <div class="control-group form-horizontal">
                <label class='control-label' ></label>
                <div class='controls control-row'>
                    <select required
                            class="input-small"
                            id="question.value"
                            name="type"
                            ng-model="choice.value"
                            ng-options="p.value as p.text for p in percentages">
                    </select>
                    <button class="btn btn-danger btn-xs" ng-click="deleteOption($index)" ><i class="icon-trash"></i></button>
                </div>
            </div>
        </div>

        <div class="control-group form-horizontal" ng-show='addBtnChoice'>
            <label class='control-label'>&nbsp;</label>
            <div class='controls'>
                <button class="btn btn-success btn-xs" ng-click="addOption()"><i class="icon-plus"></i> Add choice</button>
            </div>

            <br/><br/>
        </div>




        <div class="control-group form-horizontal" ng-show='isChapter' >
            <label class='control-label' for="question.sorting">Included questions</label>
            <div class='controls'>
                <div gims-grid-question></div>
            </div>
        </div>






        <div class="control-group form-horizontal" ng-class="{error: myForm.sorting.$invalid}" ng-show="question.id">
            <label class='control-label' for="question.sorting">Sorting</label>
            <div class='controls controls-row'>
                <input class='span1' id="question.sorting" type="text" name="sorting" ng-model="question.sorting"/>
            </div>
        </div>

    </form>

    <?php echo $this->metadata('question'); ?>
</div> <!-- /container -->
