<header class="jumbotron">
    <h2>Administration</h2>
    <p>«Manage Surveys, Users, Filters and Rules»</p>
</header>

<div class="container">

    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-12">
            <h2>Administration</h2>
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/admin/survey">
                        <p><i class="fa fa-gims-survey fa-4x"></i></p>
                        <p>Surveys</p>
                    </a>
                </li>
                <li>
                    <a href="/admin/user">
                        <p><i class="fa fa-user fa-4x"></i></p>
                        <p>Users</p>
                    </a>
                </li>
                <li>
                    <a href="/admin/filter-set">
                        <p><i class="fa fa-gims-filterset fa-4x"></i></p>
                        <p>Filter sets</p>
                    </a>
                </li>
                <li>
                    <a href="/admin/filter">
                        <p><i class="fa fa-gims-filter fa-4x"></i></p>
                        <p>Filters</p>
                    </a>
                </li>
                <li>
                    <a href="/admin/rule">
                        <p><i class="fa fa-gims-rule fa-4x"></i></p>
                        <p>Rules</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

</div> <!-- /container -->
