<!-- Main hero unit for a primary marketing message or call to action -->
<header class="jumbotron">
    <h2>Admin</h2>
    <p>«Small streams make large rivers»</p>
</header>

<div class="container">

    <!-- Example row of columns -->
    <div class="row" style="margin-top: 10px">

        <div class="span4">
            <div class="thumbnail container-survey">

                <div class="caption">
                    <h2>Survey</h2>

                    <p>Create a new survey or edit existing ones.</p>

                    <p><a href="/admin/survey" class="btn btn-primary">Manage surveys</a></p>
                </div>
            </div>
        </div>
        <div class="span4">

            <div class="thumbnail container-questionnaire">

                <div class="caption">
                    <h2>Questionnaire</h2>

                    <p>Create a new questionnaire or edit existing ones.</p>

                    <p><a href="/admin/survey" class="btn btn-primary disabled">Manage questionnaires</a>(not
                        implemented)</p>
                </div>
            </div>
        </div>
        <div class="span4">
        </div>
    </div>

</div> <!-- /container -->
