<div class="container">

    <h2>
        <ul class="breadcrumb">
            <i class="active fa fa-gims-filterset pull-right"></i>
            <li><a href="/admin/filter-set">Filter sets</a></li>
            <li class="active">{{filterSet.name}}</li>
        </ul>
    </h2>

    <form novalidate name="myForm" class="form-horizontal">

        <?php echo $this->crudButtons('filterSet'); ?>

        <br/><br/>

        <tabset style="margin-top: 20px">

            <tab heading="General" active="tabs[0]" select="selectTab(0)" >
                <div class="form-group"  ng-class="{'has-error': myForm.name.$invalid}">
                    <label class="control-label col-md-2" for="filterSet.name">Label</label>
                    <div class="col-md-6">
                        <input type="text" name="name" ng-model="filterSet.name" required/>
                    </div>
                    <div class="col-md-2">
                        <span ng-show="myForm.name.$error.required" class="help-block">Required</span>
                    </div>
                </div>
                <div class="form-group" ng-hide="isChapter" ng-class="{'has-error': myForm.filter.$invalid}">
                    <label class="control-label col-md-2"  for="filters">Filters</label>
                    <div class="col-md-8">
                        <gims-filter model="filterSet.filters"
                                     show-selection-path="true"
                                     show-edit-button="true"
                                     current-url="/admin/filter/edit/{{filter.id}}"
                                     multiple>
                        </gims-filter>

                    </div>
                    <div class='col-md-1'>
                        <span ng-show="myForm.filter.$error.required" class="col-md-1 help-block">Required</span>
                    </div>
                </div>

            </tab>

            <tab heading="Users" active="tabs[1]" select="selectTab(1)"  ng-if="filterSet.id">
                <gims-relations relation="UserFilterSet" properties="['filterSet', 'user', 'role']"></gims-relations>
            </tab>

        </tabset>

    </form>
</div>
