<div class="container">

    <h2>
        <ul class="breadcrumb">
            <li class="active"><a href="/admin/filter-set">Filter set</a></li>
        </ul>
    </h2>

    <div class="row">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search" style="width: 400px"/>
        </div>
        <div class="col-md-3 show-grid" style="text-align: right">
            <gims-link-new target="filter-set"></gims-link-new>
        </div>
    </div>

    <div ng-grid="gridOptions" class="gridStyle"></div>

</div> <!-- /container -->
