<div class="container">

    <h2>
        <ul class="breadcrumb">
            <?php echo $this->helpButton(); ?>
            <span class="active pull-right"><i class="fa fa-fw fa-gims-filterset"></i></span>
            <li class="active"><a href="/admin/filter-set">Filter set</a></li>
        </ul>
    </h2>

    <?php echo $this->helpBox('Edit the filter set\'s label and edit its filter content. For further info, see the <a target="_blank" href="http://gims.readthedocs.org/en/develop/content/filter_set.html">detailed documentation</a>.'); ?>

    <div class="row">
        <div class="col-md-9">
            <input type="text" ng-model="gridOptions.filterOptions.filterText" placeholder="Search..." class="search form-control" style="width: 400px"/>
        </div>
        <div class="col-md-3 show-grid text-right">
            <gims-link-new target="filter-set"></gims-link-new>
        </div>
    </div>

    <gims-grid api="filter-set" options="gridOptions"></gims-grid>

</div> <!-- /container -->
