<!-- Main hero unit for a primary marketing message or call to action -->
<div class="jumbotron">
    <h2>About GIMS</h2>
    <p>Learn where the project stems from and what are it’s goals.</p>
</div>

<div class="container">

    <!-- Docs nav
    ================================================== -->
    <div class="row">
        <div class="span3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix-top">
                <li class=""><a href="#point1"><i class="icon-chevron-right"></i> Point 1</a></li>
                <li><a href="#point2"><i class="icon-chevron-right"></i> Point 2</a></li>
                <li><a href="#point3"><i class="icon-chevron-right"></i> Point 3</a></li>
            </ul>
        </div>
        <div class="span9">


            <section id="point1">
                <h3>Point 1</h3>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve-
                    niam, quis nostrud exercitation ullamco laboris nisi. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            </section>


            <section id="point2">
                <h3>Point 2</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve-
                    niam, quis nostrud exercitation ullamco laboris nisi. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            </section>


            <section id="point3">
                <h3>Point 3</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve-
                    niam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commo-
                    do consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim ve-
                    niam, quis nostrud exercitation ullamco laboris nisi. Excepteur sint occaecat cupidatat non
                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

            </section>

        </div>
    </div>

</div>