<!-- Main hero unit for a primary marketing message or call to action -->
<header class="jumbotron">
    <h2>About GIMS</h2>

    <p>Learn where the project stems from and what are its goals</p>
</header>

<div class="container">

    <!-- Docs nav
    ================================================== -->
    <div class="row">

        <div class="col-md-3 bs-docs-sidebar">
            <ul class="nav nav-list bs-docs-sidenav affix-top">
                <li class=""><a href="#point1"><i class="icon-chevron-right"></i> Background</a></li>
                <li class=""><a href="#point2"><i class="icon-chevron-right"></i> Solution</a></li>
                <li class=""><a href="#point3"><i class="icon-chevron-right"></i> Goals</a></li>
                <li class=""><a href="#point4"><i class="icon-chevron-right"></i> Impact</a></li>
                <li class=""><a href="#point5"><i class="icon-chevron-right"></i> Partners and donors</a></li>
            </ul>
        </div>
        <div class="col-md-9">

            <section id="point1">

                <script type="text/javascript">
                    $(document).ready(function () {
                        $('.read-more').click(function (e) {
                            $('.hidden-read-more').toggle();
                            e.preventDefault();
                        });
                    });
                </script>
                <h2>Background</h2>

                <p>Environmental determinants are critical components of human health. It is currently estimated that a
                    quarter of the global burden of disease (3.9 million deaths) could be prevented through healthier
                    environments, including access to water, sanitation facilities and basic hygiene. To date, extensive
                    monitoring is being carried out at global, regional, country and local levels. Two monitoring
                    mechanisms
                    in place include The WHO/UNICEF Joint Monitoring Programme (JMP) for Water Supply and Sanitation and
                    The
                    UN-Water Global Analysis and Assessment of Sanitation and Drinking-Water (GLAAS). <a href="#"
                                                                                                         class="read-more">Read
                        more</a>...
                </p>

                <p class="hidden-read-more" style="display: none">These two reporting mechanisms represent a
                    complementary set of information on water and
                    development. The JMP is the official mechanism of the UN system mandated to monitor global progress
                    towards the Millenium Development Goals (MDG). JMP monitors outcomes by reporting on access and
                    coverage
                    of improved water sources and sanitation facilities globally. JMP estimates, derived primarily from
                    household surveys and census data, allow comparisons between countries over time. GLAAS, a UN-Water
                    reporting mechanism, tracks the institutional and financial capacity of countries to progress
                    towards
                    the MDG water and sanitation targets. GLAAS, for example, is able to compare improvements in service
                    levels to institutional, policy, or funding changes.
                </p>

                <p>Many more factors are implicated in the link between the environment and public health, including
                    climatic, meteorological, epidemiological, socio-economic conditions and infrastructure. As can be
                    imagined, all these public health determinants are correlated. Gaining insight into the complex
                    relationship between these variables requires a data management system which captures all relevant
                    health determinants into one global platform for analysis.
                </p>
            </section>

            <section id="point2">

                <h3>Solution</h3>

                <p>The Global Information Management System on Environment and Health (GIMS) provides the platform for
                    this
                    innovative approach to environmental disease prevention. GIMS will contain data collected through
                    national and international surveys, national censuses, scientific repositories, climate and
                    meteorological forecast systems, and GIS based data. Data will be thematic, spatial and temporal in
                    nature and will be available at regional, country and local levels.</p>
            </section>
            <section id="point3">
                <h3>
                    Goals
                </h3>

                Using a multi-disciplinary public health approach, the goals of GIMS are to:
                <ul>
                    <li>harmonize water, sanitation and hygiene monitoring mechanisms (JMP access and coverage data with
                        GLAAS
                        institutional and financial capacity data).
                    </li>
                    <li>provide insight into the correlation of environmental drivers that impact human health (access
                        to
                        water, sanitation facilities, basic hygiene, socio-economic status and climate conditions).
                    </li>
                    <li>integrate spatial and temporal data on key health determinants at local, country and regional
                        levels.
                    </li>
                    <li>provide an early warning system of health emergencies (such as cholera outbreaks) by using
                        dynamic
                        models which assess real-time environmental, meteorological, socio-economic, microbiological and
                        health
                        data.
                    </li>
                    <li>promote innovative analytical tools, with data collection, analysis, dissemination and
                        visualization
                        capacities.
                    </li>
                </ul>

            </section>
            <section id="point4">
                <h3>Impact</h3>

                <p>This global initiative provides a common framework under which the scientific community,
                    international
                    and national public health decision makers, data managers, the private sector and political leaders
                    are
                    combining efforts to achieve the elimination of environment related disease. Access to a centralized
                    data management system allows a fundamental paradigm shift from traditional “surveillance and
                    response”
                    to “prediction and prevention” –helping to save lives, optimize resource utilization, promote
                    evidence-based decision making and ensure effective policy and program implementation.</p>

            </section>
            <section id="point5">
                <h3>Partners and donors</h3>

                <p>United Nations Children’s Fund (UNICEF), UK aid (formerly UK Department for International Development
                    ,
                    DFID), Islamic Development Bank , International Centre for Diarrhoeal Disease Research, Bangladesh
                    (ICDDRB), US National Oceanic and Atmospheric Administration (NOAA), Council for Scientific and
                    Industrial Research, South Africa (CSIR), Royal Tropic Institute, Netherlands (KIT), Fraunhofer
                    Institute of Optronics, System Technologies and Image Exploitation, Germany (IOSB)</p>
            </section>

        </div>
    </div>

</div>