<div class="container">

    <!-- Docs nav
    ================================================== -->
    <div class="row">
        <div>
            <div class="input-group input-group-sm">
                <gims-cell-menu></gims-cell-menu>
                <input class="form-control text-center" />
                <span class="input-group-addon" ><i class="fa fa-fw">%</i></span>
            </div>


            <pre>{{items| json}}</pre>

            <div >Selection from a modal: {{ selected}}</div>
        </div>



        <div>okoki</div>
        <div class="dropdown clearfix open">
            <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown">
                Dropdown
                <span class="caret"></span>
            </button>

            <!-- drop down menu -->
            <ul class="dropdown-menu " >
                <li class="dropdown-header">Information</li>
                <li><a><i class="fa fa-question fa-fw"></i> some shite 1</a></li>
                <li><a><i class="fa fa-question fa-fw"></i> some shite 2</a></li>
                <li><a><i class="fa fa-question fa-fw"></i> some shite 3</a></li>
            </ul>
        </div>




        <div >
            <div class="gims-contextual-menu open" gims-position-when-rendered style=" position: absolute;">
                <ul  class="gims-dropdown-menu ">
                    <li class="dropdown-header">Information</li>
                    <li><a><i class="fa fa-question fa-fw"></i> some shite 1</a></li>
                    <li ng-repeat="item in items">
                        <a ng-click="selected.item = item">{{ item}} ssss</a>
                    </li>
                </ul>
                Selected: <b>{{ selected.item}}</b>
            </div>
        </div>
    </div>
</div>