
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="jumbotron">
    <h2>Browse</h2>
    <p>Search and query data in 3D: maps - charts - tables</p>
</div>

<div class="container">

    <!-- Example row of columns -->
    <div class="row browse">
        <div class="span4">
            <h2>Maps</h2>

            <p><i class="icon-globe icon-4x puall-left "></i></p>
        </div>
        <div class="span4">
            <h2>Charts</h2>

            <p><i class="icon-bar-chart icon-4x pulal-left "></i></p>
        </div>
        <div class="span4">
            <h2>Tables</h2>

            <p><i class="icon-table icon-4x puall-left "></i></p>
        </div>
    </div>
</div>