

<!-- Main hero unit for a primary marketing message or call to action -->
<div class="jumbotron">
    <h2>Browse</h2>
    <p>Search and query data in 3D: maps - charts - tables</p>
</div>

<div class="container">

    <!-- Example row of columns -->
    <div class="row">
        <div class="span4">
            <h2>Access</h2>
            <p>Existing users can login here:</p>
            <form class="">
                <input type="text" placeholder="Email">
                <div><input type="password" placeholder="Password"></div>
                <button type="submit" class="btn">Sign in</button>
            </form>
        </div>
        <div class="span4">
            <h2>Become</h2>
            <p>A contributor of new data or comment existing info: create an account !</p>

            <form class="">
                <div><input type="text" placeholder="Email"></div>
                <div><input type="text" placeholder="First name"></div>
                <div><input type="text" placeholder="Last name"></div>
                <button type="submit" class="btn">Create account</button>
            </form>
        </div>
        <div class="span4">
            <h2>Contact us</h2>

            <p>You can help us improve both the system and the data by sending us an email.</p>
        </div>
    </div>

</div> <!-- /container -->
