<header class="jumbotron">
    <h1>GIMS</h1>
    <p>Global Information Management System</p>
</header>

<div class="container">

    <!-- Example row of columns -->
    <div class="row">
        <div class="span4">
            <p><a class="btn btn-primary btn-large" href="about">About &raquo;</a></p>
            <p>Learn where the project stems from and what are its goals.</p>
        </div>
        <div class="span4">
            <p><a class="btn btn-primary btn-large" href="browse">Browse &raquo;</a></p>
            <p>Search and query data in 3D: maps - charts - tables.</p>
        </div>
        <div class="span4">
            <p><a class="btn btn-primary btn-large" href="contribute">Contribute &raquo;</a></p>
            <p>Ready to participate?</p>
        </div>
    </div>

</div> <!-- /container -->