<header class="jumbotron">
    <h1>GIMS</h1>
    <p>Global Information Management System on Health and Environment</p>
</header>

<div class="container">

    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <p><a class="btn btn-primary btn-lg" href="about">About &raquo;</a></p>
            <p>Learn where the project stems from and what are its goals.</p>
        </div>
        <div class="col-md-4">
            <p><a class="btn btn-primary btn-lg" href="browse">Browse &raquo;</a></p>
            <p>Search/Query charts and tables.</p>
        </div>
        <div class="col-md-4">
            <p><a class="btn btn-primary btn-lg" href="contribute">Contribute &raquo;</a></p>
            <p>Create your own dataset and compare with JMP estimations.</p>
            <p>Enter your survey results and submit them to JMP.</p>

            <p><a class="btn btn-default" href="contribute/request-roles"><i class="fa fa-unlock"></i> Ask for permissions</a></p>
        </div>
    </div>

</div> <!-- /container -->