<?php echo $this->doctype(); ?>

<html lang="en" ng-app="myApp">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('GIMS')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/favicon.ico'))
                ->prependStylesheet('/css/application.css')
                ->prependStylesheet('/lib/select2/select2.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile('/js/min/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile(array('/js/min/application.js',
                    array(
                        // CAUTION: This must be the exact same files in reverse order than in bin/build.sh

                        // Our own scripts
                        '/js/min/directives.js',
                        '/js/min/filters.js',
                        '/js/min/controllers.js',
                        '/js/min/controllers-admin.js',
                        '/js/min/services.js',
                        '/js/min/app.js',

                        // AngularJS core and libs
                        '/lib/angular-highcharts-directive/src/directives/highchart.js',
                        '/lib/ng-grid/build/ng-grid.min.js',
                        '/lib/ui-bootstrap/ui-bootstrap-tpls-0.2.0.min.js',
                        '/lib/angular-ui/build/angular-ui.min.js',
                        '/lib/angular/angular-resource.min.js',
                        '/lib/angular/angular.min.js',

                        // Non AngularJS stuff
                        '/lib/highcharts/highcharts-more.js',
                        '/lib/highcharts/highcharts.js',
                        '/lib/select2/select2.js',
                        '/lib/jquery/jquery-1.9.1.min.js',
                    )
                ))
        ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="<?php echo $this->url('home') ?>">GIMS</a>
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li><a href="/about"><?php echo $this->translate('About') ?></a></li>
                            <li><a href="/browse"><?php echo $this->translate('Browse') ?></a></li>
                            <li><a href="/contribute"><?php echo $this->translate('Contribute') ?></a></li>
                        </ul>
                    </div><!--/.nav-collapse -->

                    <div class="pull-right" ng-controller="UserCtrl">
                        <div modal="showLogin" close="cancelLogin()" options="opts">
                            <?php
                                $f = $this->zfcUserLoginWidget(array('render' => false));
                                $form = $f->loginForm;
                                $form->prepare();
                                $form->setAttribute('action', $this->url('zfcuser/login'));
                                $form->setAttribute('method', 'post');
                                $form->setAttribute('class', 'modal-form form-horizontal');

                                echo $this->form()->openTag($form);
                            ?>
                            <div class="modal-header">
                                <h3><?php echo $this->translate('Sign in'); ?></h3>
                            </div>
                            <div class="modal-body">
                                <?php echo $this->ztbFormElement($form->get('identity')) ?>
                                <?php echo $this->ztbFormElement($form->get('credential')) ?>
                                <input type="hidden" name="redirect" value="{{redirect}}" />
                            </div>
                            <div class="modal-footer">
                                <?php echo $this->formButton($form->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
                                <a class="btn cancel" ng-click="cancelLogin()"><?php echo $this->translate('Cancel'); ?></a>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>

                        <div modal="showRegister" close="cancelRegister()" options="opts">
                            <?php
                                $this->registerForm->prepare();
                                $this->registerForm->setAttribute('action', $this->url('zfcuser/register'));
                                $this->registerForm->setAttribute('method', 'post');
                                $this->registerForm->setAttribute('class', 'modal-form form-horizontal');

                                echo $this->form()->openTag($this->registerForm);
                            ?>
                            <div class="modal-header">
                                <h3><?php echo $this->translate('Create account'); ?></h3>
                            </div>
                            <div class="modal-body">
                                <?php foreach ($this->registerForm as $element):
                                    if (!$element instanceof Zend\Form\Element\Button)
                                    {
                                        echo $this->ztbFormElement($element);
                                    }
                                endforeach; ?>
                                <input type="hidden" name="redirect" value="{{redirect}}" />
                            </div>
                            <div class="modal-footer">
                                <?php echo $this->formButton($this->registerForm->get('submit')->setAttribute('class', 'btn btn-primary')) ?>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>

                        <?php if ($this->zfcUserIdentity()): ?>
                            <p class="navbar-text">
                                <?php
                                    echo $this->gravatar($this->zfcUserIdentity()->getEmail(), array('img_size' => 32)) . PHP_EOL;
                                    echo $this->zfcUserDisplayName();
                                ?>
                                <a target="_self" href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign out') ?>]</a>
                            </p>
                        <?php else: ?>
                            <?php
                                $form->setAttribute('class', 'navbar-form');
                                $form->get('identity')->setAttribute('placeholder', $form->get('identity')->getLabel());
                                $form->get('credential')->setAttribute('placeholder', $form->get('credential')->getLabel());

                                echo $this->form()->openTag($form);
                                echo $this->formInput($form->get('identity')->setAttribute('class', 'span2')) . PHP_EOL;
                                echo $this->formInput($form->get('credential')->setAttribute('class', 'span2')) . PHP_EOL;
                                echo $this->formButton($form->get('submit')) . PHP_EOL;
                            ?>
                            <input type="hidden" name="redirect" value="{{redirect}}" />
                            <a href ng-click="promptRegister()"><?php echo $this->translate('Create account') ?></a>
                            <?php echo $this->form()->closeTag(); ?>
                        <?php endif; ?>
                </div>
            </div>
        </div>
        </div>
        <div class="container">
            <div class="content" ng-view></div>

            <hr>
            <footer>
                <p class="muted"><?php echo $this->translate('Designed and built by Ecodev for WHO') ?></p>
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
