<div class="modal-body">
    <div class="row" ng-if="state == 'invalidToken'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Invalid link'); ?></h3>
            <p>Your link has expired. Request a new link by clicking on "Forgot password" for both : changing password or activate your account.</p>
        </div>
    </div>
    <div class="row" ng-if="state == 'registered'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Email activation'); ?></h3>
            <p>The account was created and an activation email was sent to <strong>{{registeredEmail}}</strong>. Activate your account by following the link in the email.</p>
        </div>
    </div>
    <div class="row" ng-if="state == 'activating'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Activating...'); ?></h3>
            <p>The account is being activated... <i class="fa fa-gims-loading"></i></p>
        </div>
    </div>
    <div class="row" ng-if="state == 'activated'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Activated'); ?></h3>
            <p>The account was successfully activated. You can now sign in with the password you chose.</p>
        </div>
    </div>
    <div class="row" ng-if="state == 'resetSent'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Reset password'); ?></h3>
            <p>A reset link has been sent to <strong>{{resetPasswordForEmail}}</strong>. Follow the link and set a new password.</p>
        </div>
    </div>
    <div class="row" ng-if="state == 'changingPassword'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Change password'); ?></h3>
            <p>Verifying link validity... <i class="fa fa-gims-loading"></i></p>
        </div>
    </div>
    <div class="row" ng-if="state == 'changePassword'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Change password'); ?></h3>
            <p>If you are not <strong>{{login.name}} ({{login.identity}})</strong>, close this window. </p>
            <form class="modal-form" name="changePasswordForm" ng-submit="changePassword()">
                <div class="form-group" ng-class="{'has-error': changePasswordForm.password.$dirty && changePasswordForm.password.$invalid}">
                    <label class="control-label" for="register-password"><?php echo $this->translate('New password'); ?></label>
                    <input type="password" name="password" id="register-password" placeholder="new password" ng-model="register.password" required ng-minlength="6"/>
                    <span ng-show="changePasswordForm.password.$error.minlength" class="help-block"><?php echo sprintf($this->translate("Minimum %u characters"), 6); ?></span>
                </div>
                <div class="form-group" ng-class="{'has-error': changePasswordForm.passwordVerify.$dirty && changePasswordForm.passwordVerify.$invalid}">
                    <input type="password" name="passwordVerify" id="register-password-verify" placeholder="confirm new password" required ui-validate=" '$value==register.password' " ui-validate-watch=" 'register.passwordVerify' " ng-model="register.passwordVerify">
                    <span ng-show="changePasswordForm.passwordVerify.$error.validator" class="help-block"><?php echo $this->translate("Passwords do not match!"); ?></span>
                </div>
                <button type="submit" name="submit" class="btn btn-primary" value="" ng-disabled="!register.password || register.password != register.passwordVerify"><?php echo $this->translate('Change password') ?> <i ng-show="state == 'registering'" class="fa fa-gims-loading"></i></button>
            </form>
        </div>
    </div>
    <div class="row" ng-if="state == 'passwordChanged'">
        <div class="col-md-12">
            <h3 class="modal-header"><?php echo $this->translate('Password changed'); ?></h3>
            <p>The password has successfully been changed. You can now sign in with the new one.</p>
        </div>
    </div>

    <div class="row" ng-if="state != 'registered' && state != 'activating' && state != 'resetSent' && state != 'changePassword' && state != 'invalidToken'">
        <div ng-class="{'col-md-12': state == 'activated' || state == 'passwordChanged'}" class="col-md-6">
            <h3 class="modal-header"><?php echo $this->translate('Sign in'); ?></h3>
            <form class="modal-form" name="loginForm" ng-submit="sendLogin()">
                <div class="alert alert-danger" ng-show="invalidUsernamePassword">
                    <span><?php echo $this->translate('Invalid username or password'); ?></span>
                </div>
                <div class="form-group" ng-class="{'has-error': userNotFound || loginForm.identity.$dirty && loginForm.identity.$invalid}">
                    <label class="control-label" for="login-email"><?php echo $this->translate('Email'); ?></label>
                    <input gims-focus type="email" class="form-control" name="identity" id="login-email" ng-model="login.identity" ng-blur="toLowerCase()" />
                    <span ng-show="loginForm.identity.$error.email" class="help-block"><?php echo $this->translate('Enter a valid email address'); ?></span>
                    <span ng-show="userNotFound" class="help-block"><?php echo $this->translate('No user has been found with this email address'); ?></span>
                </div>

                <div class="form-group">
                    <label class="control-label" for="login-password"><?php echo $this->translate('Password'); ?></label>
                    <input type="password" class="form-control" name="credential" id="login-password" ng-model="login.credential" />
                </div>

                <button type="submit" name="submit" class="btn btn-primary" value=""><?php echo $this->translate('Sign In'); ?> <i ng-show="state == 'signing'" class="fa fa-gims-loading"></i></button>

                <a class='btn text-muted' tooltip="Enter a valid e-mail" ng-if="!login.identity || loginForm.identity.$invalid">Forgot password</a>
                <a class='btn btn-link' ng-click="sendChangePassword()" ng-if="login.identity && !loginForm.identity.$invalid">Forgot password <i ng-show="state == 'reseting'" class="fa fa-gims-loading"></i></a>

                <input type="hidden" name="redirect" value="{{redirect}}">
            </form>
        </div>

        <div class="col-md-6" ng-if="state != 'activated' && state != 'passwordChanged'">
            <h3 class="modal-header"><?php echo $this->translate('Register'); ?></h3>
            <form class="modal-form" name="registerForm" ng-submit="sendRegister()">
                <div class="form-group" ng-class="{'has-error': userExisting || (registerForm.email.$dirty && registerForm.email.$error.email)}">
                    <label class="control-label" for="register-email"><?php echo $this->translate('Email'); ?></label>
                    <input type="email" class="form-control" name="email" id="register-email" required ng-model="register.email" ng-blur="toLowerCase()">
                    <span ng-show="registerForm.email.$error.email" class="help-block"><?php echo $this->translate('Enter a valid email address'); ?></span>
                    <span ng-show="userExisting" class="help-block"><?php echo $this->translate('There is already an account with this email address'); ?></span>
                </div>
                <div class="form-group" ng-class="{'has-error': registerForm.display_name.$dirty && registerForm.display_name.$invalid}">
                    <label class="control-label" for="register-name"><?php echo $this->translate('Display name'); ?></label>
                    <input id="register-name" type="text" class="form-control" name="display_name" ng-model="register.name" required ng-minlength="3"/>
                    <span ng-show="registerForm.display_name.$error.minlength" class="help-block"><?php echo sprintf($this->translate("Minimum %u characters"), 3); ?></span>
                </div>
                <div class="form-group" ng-class="{'has-error': registerForm.password.$dirty && registerForm.password.$invalid}">
                    <label class="control-label" for="register-password"><?php echo $this->translate('Password'); ?></label>
                    <input type="password" class="form-control" name="password" id="register-password" placeholder="password" ng-model="register.password" required ng-minlength="6"/>
                    <span ng-show="registerForm.password.$error.minlength" class="help-block"><?php echo sprintf($this->translate("Minimum %u characters"), 6); ?></span>
                </div>
                <div class="form-group" ng-class="{'has-error': registerForm.passwordVerify.$dirty && registerForm.passwordVerify.$invalid}">
                    <input type="password" class="form-control" name="passwordVerify" id="register-password-verify" placeholder="confirm password" required ui-validate=" '$value==register.password' " ui-validate-watch=" 'register.passwordVerify' " ng-model="register.passwordVerify">
                    <span ng-show="registerForm.passwordVerify.$error.validator" class="help-block"><?php echo $this->translate("Passwords do not match!"); ?></span>
                </div>
                <button type="submit" name="submit" class="btn btn-primary" value=""><?php echo $this->translate('Register') ?> <i ng-show="state == 'registering'" class="fa fa-gims-loading"></i></button>
            </form>
        </div>

    </div>
</div>
<div class="modal-footer">
    <a class="btn btn-default cancel" ng-click="cancelLogin()" ng-if="state != 'registered'"><?php echo $this->translate('Cancel'); ?></a>
    <a class="btn btn-default cancel" ng-click="cancelLogin()" ng-if="state == 'registered'"><?php echo $this->translate('Close'); ?></a>
</div>
