<div class="col-md-1">
    <span class="fa-stack fa-lg" ng-class="{'text-primary': activity.action == 'update', 'text-success':activity.action == 'create', 'text-danger': activity.action == 'delete'}">
        <i class="fa fa-cogs fa-stack-2x"></i>
    </span>
</div>

<div class="col-md-11">
    <h3 style="margin-top:5px;" ng-class="{'text-primary': activity.action == 'update', 'text-success':activity.action == 'create', 'text-danger': activity.action == 'delete'}">
        <span ng-switch="activity.action">
            <span ng-switch-when="update">Rule usage updated</span>
            <span ng-switch-when="create">Rule usage created</span>
            <span ng-switch-when="delete">Rule usage deleted</span>
        </span>
        <a href="" class="btn btn-default btn-xs" ng-click="activity.showDetails = !activity.showDetails"><i class="fa fa-eye"></i> View details</a>

        <a ng-if="activity.recordType == 'filterQuestionnaireUsage'" href="/admin/questionnaire/edit/{{activity.data.questionnaire.id}}#1" class="btn btn-default btn-xs"><i class="fa fa-gims-questionnaire"></i> View in questionnaire</a>
        <a ng-if="activity.recordType == 'filterQuestionnaireUsage'" href="/admin/rule/edit/{{activity.data.rule.id}}#1" class="btn btn-default btn-xs"><i class="fa fa-gims-rule"></i> View in rule</a>

        <a ng-if="activity.recordType == 'questionnaireUsage'" href="/admin/questionnaire/edit/{{activity.data.questionnaire.id}}#1" class="btn btn-default btn-xs"><i class="fa fa-gims-questionnaire"></i> View in questionnaire</a>
        <a ng-if="activity.recordType == 'questionnaireUsage'" href="/admin/rule/edit/{{activity.data.rule.id}}#1" class="btn btn-default btn-xs"><i class="fa fa-gims-rule"></i> View in rule</a>
    </h3>

    <gims-activity-changes></gims-activity-changes>
    <gims-activity-data ng-show="activity.showDetails"></gims-activity-data>
</div>

