<!-- Main hero unit for a primary marketing message or call to action -->
<div class="container">
    <form>
        <div class="row">
            <div class="span6">
                <p><gims-select api="country" model="country" placeholder="<?php echo $this->translate('Select a country') ?>" format="name" style="width:100%;"/></p>
            </div>
            <div class="span6" style="text-align: right">
                <img src="/img/jmp-logo-black" alt="Unicef logo" class="logo-chart"/>
                <img src="/img/who-logo-black.png" alt="WHO logo" class="logo-chart"/>
                <img src="/img/unicef-logo-black.png" alt="Unicef logo" class="logo-chart"/>
            </div>
        </div>
        <div class="row">
            <span class="span6">
                <p><gims-select api="filterSet" model="filterSet" placeholder="<?php echo $this->translate('Select a filter set') ?>" style="width:100%;"/></p>
            </span>
        </div>
        <div class="row">
            <span class="span2">
                <p><gims-select api="part" model="part" placeholder="<?php echo $this->translate('Select a part') ?>" style="width:100%;"/></p>
            </span>
            <span class="span2">
                <p>&nbsp;<i class="icon-loading" ng-show="isLoading"></i></p>
            </span>
        </div>
    </form>

    <div class="alert alert-info" ng-hide="chart"><i class="icon-info-sign"></i> <?php echo $this->translate('Select parameters to plot a chart here.') ?></div>

    <div class="row-fluid">
        <div class="span8">
            <chart value="chart" type="area" height="400" chart-obj="chartObj" />
        </div>
        <div class="span4">
            <div style="text-align: center; margin-bottom: 10px">
                <button ng-click="updateChart()" ng-class="{disabled: updateChartInProcess}" ng-show="pointSelected" class="btn">Update chart</button>
                <button id="btn-new-filter-set" ng-show="pointSelected" class="btn">Create new filter set</button>
            </div>
            <div ng-grid="gridOptions" class="gridStyle" ng-show="pointSelected" style="min-width: 400px"></div>
            <div style="margin-top: 10px; text-align: center">
                <button ng-click="ignoreQuestionnaire()" ng-class="{disabled: updateChartInProcess}"
                        ng-show="pointSelected" class="btn">Ignore questionnaire
                </button>
            </div>

        </div>

    </div>


</div>
