<header class="jumbotron">
    <h2>Browse</h2>
    <p>Search and query data in 3D: maps - charts - tables</p>
</header>

<div class="container">

    <!-- Example row of columns -->
    <div class="row browse">
        <div class="col-md-4">
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a>
                        <p><i class="icon-globe icon-4x"></i></p>
                        <p>Maps</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/browse/chart">
                        <p><i class="icon-bar-chart icon-4x"></i></p>
                        <p>Charts</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/browse/table/filter">
                        <p><i class="icon-table icon-4x"></i></p>
                        <p>Filters</p>
                    </a>
                </li>
                <li>
                    <a href="/browse/table/questionnaire">
                        <p><i class="icon-table icon-4x"></i></p>
                        <p>Questionnaires</p>
                    </a>
                </li>
                <li>
                    <a href="/browse/table/country">
                        <p><i class="icon-table icon-4x"></i></p>
                        <p>Countries</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>