
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="jumbotron">
    <h2>Browse</h2>
    <p>Search and query data in 3D: maps - charts - tables</p>
</div>

<div class="container">

    <!-- Example row of columns -->
    <div class="row browse">
        <div class="span4">
            <p><i class="icon-globe icon-4x"></i></p>
            <h2>Maps</h2>
        </div>
        <div class="span4">
            <a href="/browse/chart">
                <p><i class="icon-bar-chart icon-4x"></i></p>
                <h2>Charts</h2>
            </a>
        </div>
        <div class="span4">
            <p><i class="icon-table icon-4x"></i></p>
            <h2>Tables</h2>
        </div>
    </div>
</div>