
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="jumbotron">
    <h2>Browse</h2>
    <p>Search and query data in 3D: maps - charts - tables</p>
</div>

<div class="container">

    <!-- Example row of columns -->
    <div class="row browse">
        <div class="span4">
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a>
                        <p><i class="icon-globe icon-4x"></i></p>
                        <p>Maps</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="span4">
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a href="/browse/chart">
                        <p><i class="icon-bar-chart icon-4x"></i></p>
                        <p>Charts</p>
                    </a>
                </li>
            </ul>
        </div>
        <div class="span4">
            <ul class="nav nav-pills nav-pills-icon">
                <li>
                    <a>
                        <p><i class="icon-table icon-4x"></i></p>
                        <p>Tables</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>