
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="container">

    <form>
        <div class="row">
            <span class="span6">
                <p><input name="questionnaire" ui-select2="select2.questionnaire.list" ng-model="select2.questionnaire.selected" data-placeholder="<?php echo $this->translate('Select a questionnaire') ?>"  style="width:100%;"/></p>
            </span>
        </div>
        <div class="row">
            <span class="span6">
                <p><input name="filterSet" ui-select2="select2.filterSet.list" ng-model="select2.filterSet.selected" data-placeholder="<?php echo $this->translate('Select a filter') ?>"  style="width:100%;"/></p>
            </span>
            <span class="span2">
                <p>&nbsp;<i class="icon-loading" ng-show="isLoading"></i></p>
            </span>
        </div>
        <div class="row">
            <div class="span6">
                <label class="checkbox">
                    <input type="checkbox" ng-model="showOnlyTopLevel" ng-click="refresh()" /> Show only top levels
                </label>
            </div>

        </div>

    </form>

    <div class="alert alert-info" ng-hide="table"><i class="icon-info-sign"></i> <?php echo $this->translate('Select parameters to show table here.') ?></div>
    <div ng-grid="gridOptions" class="gridStyle"></div>

</div>